### ISSUE TITLE
[PORT] add recipient in BotFrameworkHttpClient.PostActivityAsync if value is null

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2077] opened 2020-04-22 00:10 UTC
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3781

Fixes: #3684

### Description
If Activity.Recipient is null, this can cause skills to throw errors as the Recipient field is expected. This PR sets Recipient to an empty ChannelAccount if the value is null.

### Context
https://github.com/microsoft/botframework-sdk/issues/5785

### Testing
Added positive and negative tests for `BotFrameworkHttpClient.PostActivityAsync()` changes

# Changed projects
* integration

**Comment by stevengum** [comment] 2020-04-22 01:45
Dupe of https://github.com/microsoft/botbuilder-js/issues/1997

Fixed by https://github.com/microsoft/botbuilder-js/pull/2067

**Closed by stevengum** 2020-04-22 01:45 UTC
