### ISSUE TITLE
The latest version of the botbuilder SDK does not appear to handle activities with name "adaptiveCard/action"

### ISSUE THREAD

**Issue by sagar-malpure** [microsoft/botbuilder-js#4111] opened 2022-02-10 11:38 UTC
The latest version of the botbuilder SDK does not appear to handle activities with name "adaptiveCard/action". There is a method for handling this in "TeamsActivityHandler" Class. However, the "onInvokeActivity" does not forward any requests to it. Thus, an invocation of this type always leads to a 501 Not Implemented error.

![image](https://user-images.githubusercontent.com/85691087/153401356-33d6a2f3-096c-4d6e-b378-08ee12d36f4d.png)

https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts#L518

**Comment by stevkan** [comment] 2022-02-11 02:01
@sagar-malpure, the SDK has always returned a '501 Not Implemented' error on the `handleAdaptiveCardAction()` activity handler. This is observable when looking at the original [commit](https://github.com/microsoft/botbuilder-js/commit/ef2b7af578a5c050b14f6b63f72d28740f4adb58#).

This is by design. As the class methods are able to be overwritten, you can add your own custom logic in order to get the desired functionality you are seeking when 'adaptiveCard/action' activities arrive.

Closing this as resolved.

**Closed by stevkan** 2022-02-11 02:01 UTC
Labels: customer-reported, Bot Services

**Comment by sarthair** [comment] 2022-02-11 07:18
@stevkan Indeed. However, the` TeamsActivityHandler.onInvokeActivity` does not seem to detect/forward activities of type  `adaptiveCard/action`. Therefore, even if the` handleAdaptiveCardAction()` is overwritten, the activities of type `adaptiveCard/action` will lead [here](https://github.com/microsoft/botbuilder-js/blob/12410dfa3620f8e4859dcb45b5ce858ee57264e4/libraries/botbuilder/src/teamsActivityHandler.ts#L167).
