### ISSUE TITLE
What is the purpose of this strange use of array.filter?

### ISSUE THREAD

**Issue by benbrown** [Microsoft/botbuilder-js#380] opened 2018-08-28 13:56 UTC
There are a handful of places in the code there is a construction like this, where filter is being called but the filter function simply returns the value unchanged:

```
 const list: Choice[] = (choices || []).map(
        (choice: Choice) => typeof choice === 'string' ? { value: choice } : choice
    ).filter(
        (choice: Choice) => choice // TODO: does this do anything?
    );
```

What is the point of calling filter like this?

**Comment by Stevenic** [comment] 2018-08-28 16:07
It would technically be filtering out any null/undefined choices.  I can't remember why it was added but we can remove it.

**Comment by stevengum** [comment] 2018-08-28 16:18
Whoops, accidentally closed this; sorry everyone!

**Comment by sgellock** [comment] 2018-09-05 20:58
by design

**Closed by sgellock** 2018-09-05 20:58 UTC
