### ISSUE TITLE
first time through 'npm test' failed

### ISSUE THREAD

**Issue by roalexan** [Microsoft/botbuilder-js#381] opened 2018-08-28 14:32 UTC
Followed the instructions through, then after running 'npm test' I got:

```bash
lerna success - botframework-schema
module.js:549
    throw err;
    ^

Error: Cannot find module 'fetch-ponyfill'
    at Function.Module._resolveFilename (module.js:547:15)
```

so, I tried 'npm install fetch-ponyfill' but got:

```bash
> botbuilder-packages@ test C:\microsoft\repos\botbuilder-js
> lerna run build && nyc mocha "libraries/bot*/tests/*.test.js"

lerna info version 2.9.0
lerna info versioning independent

> botframework-schema@4.0.0-preview1.2 build C:\microsoft\repos\botbuilder-js\libraries\botframework-schema
> tsc

lerna ERR! build Errored while running script in 'botframework-config'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 2
lerna ERR! npm ERR! botframework-config@4.0.0-preview1.2 build: `tsc`
lerna ERR! npm ERR! Exit status 2
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the botframework-config@4.0.0-preview1.2 build script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\roalexan\AppData\Roaming\npm-cache\_logs\2018-08-28T14_19_30_354Z-debug.log
lerna ERR!
lerna ERR! > botframework-config@4.0.0-preview1.2 build C:\microsoft\repos\botbuilder-js\libraries\botframework-config
lerna ERR! > tsc
lerna ERR!
lerna ERR! src/botConfiguration.ts(8,26): error TS2307: Cannot find module 'read-text-file'.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\microsoft\repos\botbuilder-js\node_modules\lerna\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: npm run build
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! botframework-config@4.0.0-preview1.2 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the botframework-config@4.0.0-preview1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\roalexan\AppData\Roaming\npm-cache\_logs\2018-08-28T14_19_30_354Z-debug.log

> botframework-config@4.0.0-preview1.2 build C:\microsoft\repos\botbuilder-js\libraries\botframework-config
> tsc

src/botConfiguration.ts(8,26): error TS2307: Cannot find module 'read-text-file'.
```

So, I started over, and the second time through 'npm test' seemed to work.

**Comment by stevengum** [comment] 2018-08-29 23:20
@roalexan, can you specify which instructions you were following? Were they the instructions in the [Wiki](https://github.com/Microsoft/botbuilder-js/wiki/Building-the-SDK)?

**Comment by roalexan** [comment] 2018-08-30 12:37
Yes, following instructions top-down.

**Comment by stevengum** [comment] 2018-09-15 18:01
@roalexan, sorry for the delay... I created a new clone of the repo and did the following commands after navigating to the root of the project:

```bash
cd tools
npm i
cd ..
lerna bootstrap --hoist
npm test
```

and was unable to reproduce the error. Since I couldn't repro and since you're unblocked I'm going to close this issue for now.

If you or if anyone else gets this issue please mention myself @stevengum or **stevenic** for us to open again and investigate.

**Closed by stevengum** 2018-09-15 18:01 UTC
Labels: Approved, bug

**Comment by roalexan** [comment] 2018-09-17 15:16
Closing this bug sounds good, since I started over and couldn't reproduce.
