### ISSUE TITLE
Receives UnhandledPromiseRejectionWarning message during bot SSO 

### ISSUE THREAD

**Issue by wenytang-ms** [microsoft/botbuilder-js#4352] opened 2022-10-31 08:43 UTC
## Versions
"botbuilder": "^4.15.0".
Node.js 16-latest
chrome-latest
windows-latest

## Describe the bug
Try this sample when the bot `onInvokeActivity` directly return 412 in `server/bots/botActivityHandler.js` the app crash down because `BotFrameworkAdapter.processActivity` throw exception once there is a 412 response but in the `index.ts` don't handle this exception.

```ts
Bot Started, restify listening to http://[::]:3978
Debugger attached.
/Users/kimjason/projects/teams-apps/pradeep-sso/query-org-user-with-message-extension-sso/bot/node_modules/botbuilder/src/botFrameworkAdapter.ts:1275
                throw new Error(`BotFrameworkAdapter.processActivity(): ${status} ERROR`);
                      ^
Error: BotFrameworkAdapter.processActivity(): 412 ERROR
    at BotFrameworkAdapter.<anonymous> (/Users/kimjason/projects/teams-apps/pradeep-sso/query-org-user-with-message-extension-sso/bot/node_modules/botbuilder/src/botFrameworkAdapter.ts:1275:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kimjason/projects/teams-apps/pradeep-sso/query-org-user-with-message-extension-sso/bot/node_modules/botbuilder/lib/botFrameworkAdapter.js:12:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Waiting for the debugger to disconnect...
[nodemon] app crashed - waiting for file changes before starting...
```
## To Reproduce
1. clone the [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso/nodejs)
2. do as the sample readme
3. you may update the code in `onInvokActivity` to return 412 directly in `server/bots/botActivityHandler.js`

## Expected behavior
The App should not crash down.

## Screenshots
![image](https://user-images.githubusercontent.com/75360946/198967105-025657f2-7cb5-40a8-864a-bd1a8d94ba87.png)

## Additional context
Or any other suggestion?

**Comment by ramfattah** [comment] 2022-10-31 17:53
Hi @wenytang-ms, we are investigating.

**Comment by ramfattah** [comment] 2022-11-03 22:47
Thanks @wenytang-ms, I was able to reproduce this issue in Teams channel.

Sharing the steps I took:
1. Cloned [sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso/nodejs)
2. Update `botbuilder` and `botbuilder-dialogs` to version **4.15.0**
3. Modified the onInvokActivity method to return 412 directly in `server/bots/botActivityHandler.js`
     ```js
    async onInvokeActivity(context) {
        const response = {
            status: 412
        };
        return response;
      }
     ```
4. Followed the readme [here ](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-sso/nodejs)to set up the bot and SSO
5. Tested the bot in Teams channel through Ngrok
6. The following error showed up in terminal
```ps
npm start                                                                                                                                    in pwsh at 15:31:35

> teams-bot@1.0.0 start F:\temp\Microsoft-Teams-Samples\samples\app-sso\nodejs
> node ./index.js

Server listening on http://localhost:4001
Running dialog with Message Activity.
(node:37692) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 412 ERROR
    at BotFrameworkAdapter.<anonymous> (F:\temp\Microsoft-Teams-Samples\samples\app-sso\nodejs\node_modules\botbuilder\lib\botFrameworkAdapter.js:746:27)
    at Generator.next (<anonymous>)
    at fulfilled (F:\temp\Microsoft-Teams-Samples\samples\app-sso\nodejs\node_modules\botbuilder\lib\botFrameworkAdapter.js:12:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37692) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37692) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Running dialog with Message Activity.
User Image Not Found!!
```

**Comment by ramfattah** [comment] 2022-11-03 22:56
Hi @JuanAr,

It appears we are able to repro this issue. Assigned this to you.

Please let me know if you have any questions. 
Thanks.

**Comment by JuanAr** [comment] 2022-11-07 15:20
> Hi @JuanAr,
> 
> It appears we are able to repro this issue. Assigned this to you.
> 
> Please let me know if you have any questions. Happy to provide additional info. Thanks.

Hi @ramfattah, thanks for reporting and details. We added this issue to our backlog and we'll be tackling it next week.

Thanks,
Juan

**Comment by johnataylor** [comment] 2022-11-14 19:09
@JuanAr any update on this?

**Comment by ceciliaavila** [comment] 2022-11-16 18:41
> @JuanAr any update on this?

Hi @johnataylor, we reproduced the issue and we are investigating the cause. We'll let you know as soon as we have more information.
Thanks.

**Comment by ceciliaavila** [comment] 2022-11-17 19:32
Hi everyone,
We found a [similar issue](https://github.com/microsoft/botbuilder-js/issues/3601) that was closed because, for SSO flows, the 412 errors are frequent, and in case you want to ignore them, you should catch them in the bot's code.
Additionally, as _BotFrameworkAdapter_ is deprecated, the recommended path is to use _CloudAdapter_.
We tested the sample using _CloudAdapter_, and the app doesn't crash when facing 412 errors because it doesn't get any _UnhandledPromiseRejectionWarnings_.
We believe this issue should be closed, and we recommend applying one of the above solutions.

**Comment by johnataylor** [comment] 2022-11-18 19:11
@ceciliaavila thanks for the update, closing the issue

**Closed by johnataylor** 2022-11-18 19:11 UTC
Labels: bug, backlog, Bot Services, customer-replied-to
