### ISSUE TITLE
Duplicated 'entities' are reported in the 'activity' whenever mentioned on Teams.

### ISSUE THREAD

**Issue by mkm-dz** [microsoft/botbuilder-js#4379] opened 2022-12-02 20:38 UTC
## Versions
What package version of the SDK are you using.
 **botbuilder": "4.18.0",
 botframework-directlinejs": "0.15.1"**

What nodejs version are you using
**v16.6.2**

What browser version are you using
**109.0.1518.5 (Official build) dev (64-bit)** 

What os are you using
**Windows 10**

## Describe the bug
In Microsoft teams when someone is mentioned the bot `activity` is reporting back duplicate `entities` (same id but different name) whenever there is a space in the name 

## To Reproduce

On a `Teams` channel:
- Mention two people (plus the bot)
-e.g Hi `@FirstName Lastname` and `@Firstname2 Lastname2`

In this example assume "@FirstName Lastname" is a single person and "@Firstname2 Lastname2" is another one.

## Expected behavior
Some weeks ago the behavior was to return 1 entity per mention (on the `entities` array). In the previous example it would a similar JSON to:

contents of `activity.entities`
```
[
    {
        "mentioned": {
            "id": "FAKEID1",
            "name": "FirstName LastName"
        },
        "text": "<at>FirstName LastName</at>",
        "type": "mention"
    },
    {  
        "mentioned": {
            "id": "FAKEID2",
            "name": "FirstName2 LastName2"
        },
        "text": "<at>FirstName2 LastName2</at>",
        "type": "mention"
    },
    {
        "locale": "en-US",
        "country": "US",
        "timezone": "America/Los_Angeles",
        "type": "clientInfo"
    }
]

```
## Actual behavior
It currently returns 4 entities 2 pairs with the same id but different name:
contents of `activity.entities` (please note the id)

```
[
    {
        "mentioned": {
            "id": "FAKEID1",
            "name": "FirstName"
        },
        "text": "<at>FirstName</at>",
        "type": "mention"
    },
    {
        "mentioned": {
            "id": "FAKEID1",
            "name": "LastName"
        },
        "text": "<at>LastName</at>",
        "type": "mention"
    },
    {
        "mentioned": {
            "id": "FAKEID2",
            "name": "FirstName2"
        },
        "text": "<at>FirstName2</at>",
        "type": "mention"
    },
    {
        "mentioned": {
            "id": "FAKEID2",
            "name": "LastName2"
        },
        "text": "<at>LastName2</at>",
        "type": "mention"
    },
    {
        "locale": "en-US",
        "country": "US",
        "timezone": "America/Los_Angeles",
        "type": "clientInfo"
    }
]

```

**Comment by ramfattah** [comment] 2022-12-05 18:43
Thanks @mkm-dz, we are looking into this.

**Comment by ramfattah** [comment] 2022-12-13 18:34
Hi @mkm-dz,

I was able to repro this this using sample [bot-conversation/nodejs/](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/nodejs) on Teams channel.

Sharing the steps to repro:
1. Clone sample [bot-conversation/nodejs/](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/nodejs)
2. Follow the [readme](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/nodejs#readme) to setup the bot from your local environment
3. Run the bot in Teams channel
4. @ mention 2 people  plus the bot in message area
     * > ex: hi @firstname lastname and @firstname lastname (@botname)
5. Notice the ngrok /api/message post request
```json

  "entities": [
       // mention person 1
        {
            "mentioned": {
                "id": "UniqueId1",
                "name": "First name"
            },
            "text": "<at>First name</at>",
            "type": "mention"
        },
        {
            "mentioned": {
                "id": "UniqueId1",
                "name": "Last name"
            },
            "text": "<at>Last name</at>",
            "type": "mention"
        },
        {
            "mentioned": {
                "id": "UniqueId1",
                "name": "(Guest)"
            },
            "text": "<at>(Guest)</at>",
            "type": "mention"
        },

       // mention person 2
        {
            "mentioned": {
                "id": "UniqueId2",
                "name": "First name"
            },
            "text": "<at>First name</at>",
            "type": "mention"
        },
        {
            "mentioned": {
                "id": "UniqueId2",
                "name": "Last name"
            },
            "text": "<at>Last name</at>",
            "type": "mention"
        },
        {
            "mentioned": {
                "id": "UniqueId2",
                "name": "(TEKsystems,"
            },
            "text": "<at>(TEKsystems,</at>",
            "type": "mention"
        },
        {
            "mentioned": {
                "id": "UniqueId2",
                "name": "Inc.)"
            },
            "text": "<at>Inc.)</at>",
            "type": "mention"
        },

       // mention bot
        {
            "mentioned": {
                "id": "UniqueId3",
                "name": "TeamsConversationBot"
            },
            "text": "<at>TeamsConversationBot</at>",
            "type": "mention"
        },
```

**Comment by ramfattah** [comment] 2022-12-13 18:35
@mkm-dz, I'm not sure if this is by design or a bug.

I will discuss with the engineering team for next steps.
Thanks.

**Comment by ramfattah** [comment] 2023-01-04 18:56
Hi @mkm-dz,

I've notified the Microsoft "Teams" team about this issue. Will report back as soon as there are updates.
Thanks.

**Comment by mkm-dz** [comment] 2023-01-05 17:49
Thank you @ramfattah for the help and for keeping the thread updated. FWIW this was a recent change (double entries) which points makes me believe this was an unintended change, but I agree, let's wait for the MS Teams comments.

**Comment by ramfattah** [comment] 2023-01-10 13:10
Hi @mkm-dz, 

Microsoft Teams team were also able to reproduce this issue and raised a bug for it.
We will let you know once we get updates on it.

Thanks.

**Comment by ramfattah** [comment] 2023-02-06 19:30
I pinged Teams team today for a friendly reminder regarding this ticket.
As soon as there are updates, we'll let you know.

Thanks for your patience @mkm-dz.

**Comment by ramfattah** [comment] 2023-09-22 03:50
Transferred to Microsoft-Teams-Samples repository:
https://github.com/OfficeDev/Microsoft-Teams-Samples/issues/969

**Closed by ramfattah** 2023-09-22 03:50 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to, ExemptFromDailyDRIReport, Area: Teams
