### ISSUE TITLE
BotFrameworkAdapter.processActivity(): 500 ERROR - Error: Unknown

### ISSUE THREAD

**Issue by textminer** [Microsoft/botbuilder-js#885] opened 2019-04-22 17:31 UTC
## Versions
SDK v4.
NodeJS 10.15.2
Azure + MS Teams channel
Windows

## Describe the bug
Bot gives HTTP Error 500 while calling any of my dialogs. Application works great on Emulator. I found that it calls twice the Bot method: async onTurn(turnContext). 
I checked that https://github.com/Microsoft/botbuilder-js/issues/249 is not the case since I disconfigured QnA Maker and my LUIS quota is ok:

![imagen](https://user-images.githubusercontent.com/38899601/56514073-a68f5380-650a-11e9-9edd-0756ef41d966.png)

## To Reproduce
1. MS Team Channel
2. Invoke any of the dialogs that prompts the user or shows more than 1 card
3. Bot throws this error twice:

 [onTurnError]: Error: Unknown
BotFrameworkAdapter.processActivity(): 500 ERROR - Error: Unknown
(node:4468) UnhandledPromiseRejectionWarning: Error: Error: Unknown
    at BotFrameworkAdapter.processActivity (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:469:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4468) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)

My dependencies are:
    "dependencies": {
        "axios": "^0.18.0",
        "botbuilder": "^4.2.0",
        "botbuilder-ai": "^4.3.4",
        "botbuilder-azure": "^4.3.4",
        "botbuilder-dialogs": "^4.3.4",
        "botframework-config": "^4.2.0",
        "dotenv": "^6.1.0",
        "fs": "0.0.1-security",
        "request-promise": "^4.2.4",
        "restify": "^7.2.3",
        "sp-request": "^2.1.3",
        "spsave": "^3.1.5"
    },

I suspect that when the bot needs to show more than 5 cards one after the other this error is thrown. With less than 6 cards sometimes isn't reproduced. And the only channel that is failing with is MS Teams.
Cards could have images, or could be plain text.

I wonder how you would try to reproduce it. Do you want the Bot Id? Or one of the dialogs classes?

## Expected behavior
This issue is not reproducible using local environment with same NodeJS version and the Emulator as is happening on Azure / MS Teams. I even tried the Web Channel as is not reproducible either.

[bug]

**Comment by v-kydela** [comment] 2019-04-23 21:17
@textminer - What type of card are they? Are the cards being sent in the same message or separate messages?

**Comment by textminer** [comment] 2019-04-24 13:21
They are separate thumbnail cards:

`function createThumbnailCardAnonymousCaseStudies(url, title, mimeType) {
    var thumbnailImage = thumbnailImageIcon(mimeType);

    return CardFactory.thumbnailCard(
        title,
        CardFactory.images([process.env.AZURE_STORAGE_HOST + "/icons/" + thumbnailImage]),
        CardFactory.actions([
            {
                type: 'openUrl',
                title: "File Link",
                value: url
            }
        ]),          
    );
}

for (var i = 0; i < sharepointFiles.length; i++) {
     var card = globalEntities.createThumbnailCardAnonymousCaseStudies(longFolder + sharepointFiles[i],     sharepointFiles[i], globalEntities.getFileExtension(sharepointFiles[i]));
	await turnContext.sendActivity({ attachments: [card] });
}`

And even doing multiple (more than 5 or 6):
`await turnContext.sendActivity("some text");`

the error is thrown.

**Comment by v-kydela** [comment] 2019-04-24 16:26
@textminer - Just to make sure I'm understanding you correctly, are you saying the error occurs even when you send a text-only activity with no attachments? So the error has nothing to do with cards?

**Comment by textminer** [comment] 2019-04-24 16:36
Exactly, the error is more related to a channel issue (with Teams), rather than which content I send.

**Comment by textminer** [comment] 2019-04-24 17:02
I'm invoking same dialogs on Azure Web Chat and on Teams. First works perfect, second doesn't.

**Comment by textminer** [comment] 2019-04-24 17:56
I enabled appinsights for the bot. I send one message to the bot using Teams that invokes a dialog. That is seen as two requests on the graph, whereas if I send same message using Azure Web Chat it's log correctly as only one request:

![imagen](https://user-images.githubusercontent.com/38899601/56681907-c48ebc80-66a0-11e9-82f0-1378f3a574d7.png)

**Comment by textminer** [comment] 2019-04-24 18:18
Inspecting App Insights transaction logs I found HTTP 429:

![imagen](https://user-images.githubusercontent.com/38899601/56683475-01a87e00-66a4-11e9-9371-ee00fb832c95.png)

Inspecting the User Flow:

![imagen](https://user-images.githubusercontent.com/38899601/56683597-3f0d0b80-66a4-11e9-8a1e-599954ec665f.png)

**Comment by v-kydela** [comment] 2019-04-24 19:04
@textminer - I have successfully reproduced this in with the Node SDK. I cannot reproduce it in .NET, but it's unclear whether that's because the .NET SDK contains safeguards to prevent it or because of random happenstance. It's also unclear why this is only happening in Teams. As you might be able to guess, [HTTP 429](https://httpstatuses.com/429) means too many messages are being sent.

I tested in Facebook, GroupMe, Kik, Skype, Slack, Telegram, and Twilio. Kik and Slack seem to go pretty fast, but they still just send each message one after the other. Teams seems to try and send a bunch of messages at once. I wonder if it's a problem with the Teams connector.

My recommendation is to just send one message instead of many. Since you want to send cards, remember that one message can contain multiple attachments either as a list or a carousel. If you still want to send multiple messages you could try artificially waiting between messages, or you could switch to the .NET SDK.

Since there does seem to be a bug here, I am going to transfer this issue back to the SDK team.

**Comment by v-kydela** [comment] 2019-04-24 19:24
@textminer - Actually, I've changed my mind. I just tried updating to botbuilder 4.3.4 and the issue stopped occurring. Perhaps the bug has already been fixed. Please update your NPM packages and see what happens.

**Comment by textminer** [comment] 2019-04-24 19:46
Here's the pattern for every broken dialog transaction. It's seen duplicate below and ends with a HTTP 429 at the end: 

![imagen](https://user-images.githubusercontent.com/38899601/56688962-5fdb5e00-66b0-11e9-94f4-37ddfc998ec2.png)

I believe this must be related to, which this is not the cause, it's the consequence of: 
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/general/rate-limit

**Comment by v-kydela** [comment] 2019-04-24 19:52
@textminer - Can you go ahead and tell me what botbuilder version you're using?

**Comment by textminer** [comment] 2019-04-24 20:10
Finally, I could make the MS Teams channel work only if I introduce a sleep of 500 ms between every await stepContext.context.sendActivity() calls. This is definately related with specific Teams channel rate limits.
The botAdapter should we trapping the trace of the HTTP 429.

Could you please advise what that rate is?

**Comment by v-kydela** [comment] 2019-04-24 20:35
@textminer - Are you seeing the posts where I'm asking you what botbuilder version you're using? You can use `npm list` to check the versions of all your packages.

**Comment by textminer** [comment] 2019-04-25 13:05
Hi @v-kydela, I'm using botbuilder v4.3.4. Thanks for your support. Sure, I will workaround it adding a sleep time between cards of 500 ms.

+-- botbuilder@4.3.4
| +-- @types/filenamify@2.0.2
| | `-- filenamify@2.1.0 deduped
| +-- @types/node@10.14.4
| +-- async-file@2.0.2
| | `-- rimraf@2.6.3
| |   `-- glob@7.1.3 deduped
| +-- botbuilder-core@4.3.4
| | +-- assert@1.4.1
| | | `-- util@0.10.3
| | |   `-- inherits@2.0.1
| | `-- botframework-schema@4.3.4
| +-- botframework-connector@4.3.4
| | +-- @azure/ms-rest-js@1.2.6
| | | +-- axios@0.18.0 deduped
| | | +-- form-data@2.3.3 deduped
| | | +-- tough-cookie@2.5.0 deduped
| | | +-- tslib@1.9.3
| | | +-- uuid@3.3.2 deduped
| | | `-- xml2js@0.4.19
| | |   +-- sax@1.2.4
| | |   `-- xmlbuilder@9.0.7 deduped
| | +-- @types/jsonwebtoken@7.2.8
| | | `-- @types/node@10.14.4 deduped
| | +-- @types/node@10.14.4 deduped
| | +-- base64url@3.0.1
| | +-- botframework-schema@4.3.4 deduped
| | +-- form-data@2.3.3
| | | +-- asynckit@0.4.0
| | | +-- combined-stream@1.0.7 deduped
| | | `-- mime-types@2.1.22 deduped

**Comment by v-kydela** [comment] 2019-04-25 18:36
Hmm, that's interesting that you're still getting the issue in 4.3.4 and I'm not. In any case, I don't know that there's any specific rate you need to use, since the issue is so inconsistent. 500 ms is probably long enough, but my recommendation is still to just send fewer messages. Since you seem to be satisfied with your workaround, I will close this issue now. Thank you for posting!

**Closed by v-kydela** 2019-04-25 18:36 UTC
Labels: Support

**Comment by dkbhadeshiya** [comment] 2019-08-01 09:58
Hey, we are somehow facing similar issue right now. 
We are getting "429 Too many Requests". 
This was working fine previously. Just started causing errors in 2 days.

**Comment by textminer** [comment] 2019-08-01 19:39
Hi @dkbhadeshiya, the issue is not solved, you´ll need to slow down the load of messages that the bot answers. I made a workaround invoking a sleep function with 500+ ms among messages to stop receiving that error.
    async sleep(millis) {
        return new Promise(resolve => setTimeout(resolve, millis));
    }

**Comment by Aleimar** [comment] 2020-03-13 07:08
Hello! Is there any update in this issue, I am facing the same error in facebook channel. It was actually working just yesterday and now facebook won't send the bot the "name" of user who messaged the bot. Thanks!

**Comment by Aleimar** [comment] 2020-03-14 02:47
hey @v-kydela , the bot was working fine now. To be clear, I didn't do any changes in the bot, but today it miraculously changed to its normal operations. I just have to ask if there was some changes in the bot channels at that time? If so, where can we have real time updates about these changes, (as some of it might cause major business impact). Thanks!

And in response to the Graph API question in stackoverflow. See this https://developers.facebook.com/docs/graph-api/reference/user/  where I just used the curl to get last name, first name and profile picture of the user. Thanks!
