### ISSUE TITLE
[Bug?] Confirm Prompt does not consider custom choices unless numbers are allowed

### ISSUE THREAD

**Issue by levinmr** [microsoft/botbuilder-js#1486] opened 2019-12-09 19:57 UTC
## Versions
What package version of the SDK are you using.
4.6.2
What nodejs version are you using
10.15.3
What browser version are you using
n/a
What os are you using
macOS 10.15.1

## Describe the bug
When attempting to provide custom choices for a confirm prompt in botbuilder-dialogs, the choices are not used when recognizing user input unless choiceOptions.includeNumbers is set to true

## To Reproduce
1. Extend confirm prompt with custom choices:
```javascript
class CustomConfirmPrompt extends ConfirmPrompt {
  constructor(id) {
    super(id);

    this.choiceOptions = { includeNumbers: false };  // If you set this option to true, then the custom choices get used
    this.confirmChoices = [
      { value: 'Yes', synonyms: ['y'] },
      { value: 'No', synonyms: ['n'] }
    ];
  }
```
2. Begin the confirm prompt
3. Enter a custom choice (in this case 'n')
4. See that the input is not accepted

## Expected behavior
When ConfirmPrompt.confirmChoices is set, the custom confirm choices should be considered when recognizing user input

## Additional context
the if condition on this line seems to be the issue (but it's very hard to tell what's going on in the surrounding function):
https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts#L117

[bug]

**Comment by mdrichardson** [comment] 2019-12-10 19:09
@levinmr This is expected behavior, although I see I understand it isn't ideal. As a workaround, you can use ChoicePrompt.

**Why this is "expected**

ConfirmPrompt, by default, uses a boolean recognizer from [Recognizers-Text](https://github.com/microsoft/Recognizers-Text/blob/master/JavaScript/packages/recognizers-choice/src/choice/choiceRecognizer.ts#L19), which recognizes/converts "Yes" in a given language to true/1 and "No" to false/0. It does not account for synonyms like "y" or "n".

Since ConfirmPrompt accepts `Choice[]`, which can contain `synonyms`, I see how this is somewhat confusing.

When you pass in `choiceOptions.includeNumbers`, it defaults to using ChoiceRecognizer's Recognizer, which does accept synonyms.

I believe this could be fixed by removing [the condition check you linked](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/prompts/confirmPrompt.ts#L117) and simply sending any failed response through the ChoiceRecognizer, but the dev team may prefer we push you/others to use ChoicePrompt for things like this.

**Comment by levinmr** [comment] 2019-12-30 14:01
Is there any followup here?

**Comment by mdrichardson** [comment] 2019-12-30 18:08
@levinmr Since this has a workaround, it's kind of a low-priority/backlog kind of thing. I shot an email out to the appropriate folks a little before the holidays and haven't heard a decision. I pinged them again this morning. I'll update once I have an answer. The path forward is basically going to be either:

•	Use ChoicePrompt when you want synonyms for yes/no in ConfirmPrompt, or
•	We'll make a PR that sends unrecognized ConfirmPrompt responses through ChoiceRecognizer so it can detect synonyms.

**Comment by cleemullins** [comment] 2019-12-31 18:40
@levinmr The Choice Prompt, as @mdrichardson points out, seems like it would be a viable alternative. 

Changes to the Confirm Prompt will have a longer turnaround (our next release is scheduled for March) and may not be feasible due to back-compat issues.

**Closed** 2020-01-01 17:08 UTC
Labels: Bot Services, customer-replied-to, customer-reported
