### ISSUE TITLE
[PORT] SSO Protocol Support

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1781] opened 2020-02-24 22:31 UTC
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3360

fixes #3356
Added schema updates, token service API calls, and OAuthPrompt updates to support SSO (single sign on) protocol operations for user login flows.

@Ted and @gabog , can you make sure your skill OAuth calls are still right?

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Adaptive
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder
* Microsoft.Bot.Connector
* Microsoft.Bot.Schema
* Swagger
* integration
* Microsoft.Bot.Builder.Dialogs.Tests
* Microsoft.Bot.Builder.Tests

**Comment by carlosscastro** [comment] 2020-02-28 18:12
Duplicate of https://github.com/microsoft/botbuilder-js/issues/1680

**Closed by carlosscastro** 2020-02-28 18:12 UTC
