### ISSUE TITLE
Audit issue with dependent package xmldom

### ISSUE THREAD

**Issue by IrishEamon** [microsoft/botbuilder-js#3928] opened 2021-09-17 11:20 UTC
## Versions
What package version of the SDK are you using: Latest (4.14.1)
What nodejs version are you using: Node v14.17.0, NPM v7.21.0
What browser version are you using: Chrome
What os are you using: MacOS - Big Sur

## Describe the bug
The package fails npm audit due to an issue with the dependent package xmldom, according to this link this issue can be fixed by using the @xmldom/xmldom (>=0.7.0) package instead: https://www.npmjs.com/advisories/1769

## To Reproduce
Steps to reproduce the behaviour:
1. Create a blank npm project
2. Run npm i botbuilder
3. Run npm audit

## Expected behaviour
Npm audit should not report any issues with the package.

## Screenshots
![image](https://user-images.githubusercontent.com/28571800/133774253-f298fed1-6b54-4a1e-8a14-27e70bff2e91.png)

**Comment by joshgummersall** [comment] 2021-09-17 15:57
Closing as dupe of https://github.com/microsoft/botbuilder-js/issues/3916

**Closed by joshgummersall** 2021-09-17 15:57 UTC
Labels: bug, needs-triage
