### ISSUE TITLE
Duplication membersAdded event

### ISSUE THREAD

**Issue by Serginyo90** [microsoft/botbuilder-js#4377] opened 2022-11-24 15:02 UTC
## Version
JavaScript "botbuilder": "4.14.0",

## Describe the bug
Give a clear and concise description of what the bug is.
We receive 2 or 4 events when user installs our application.

## Expected behavior
Receive event once

## Additional context
```{
    "membersAdded": [
        {
            "id": "29:1Iat8W8y5w9RxIgqFnDUqJlJalpDXC5jlXWG3hYzfczu25fn_gNbbc6WV7V36GbpgvQjpt8_w5nHuW_os7d",
            "aadObjectId": "9272a828-5c43-4a1c-8a15-e315f8a8"
        },
        {
            "id": "28:331df719-bfd2-4fcc-aa91-f08bc21a"
        }
    ],
    "type": "conversationUpdate",
    "timestamp": "2022-11-12T12:57:45.190Z",
    "id": "f:884a2807-d9d0-d4cb-ffd6-eec40244",
    "channelId": "msteams",
    "serviceUrl": "https://smba.trafficmanager.net/amer/",
    "from": {
        "id": "29:1Iat8W8y5w9RxIgqFnDUqJlJalpDXC5jlXWG3hYzfczu25fn_gNbbc6WV7V36GbpgvQjpt8_w5nHuW_os7d",
        "aadObjectId": "9272a828-5c43-4a1c-8a15-e315f8a8"
    },
    "conversation": {
        "conversationType": "personal",
        "tenantId": "f8ed7ee1-1d5c-48b5-b6c3-6a31e6fc",
        "id": "a:18hXVgntuPkzeTp8DS4JaeE7ua5b9sk24t8WVVfeGEb-Lt0Idw_ZOEAbWq9sGopVv6FzGM7BqZjyLv985oC4SwVjrjpMKumbK2UOj128CpWCnFvJdKQ-Xxdgz9NsK"
    },
    "recipient": {
        "id": "28:331df719-bfd2-4fcc-aa91-f08bc21a",
        "name": "ProHabits Bot"
    },
    "channelData": {
        "tenant": {
            "id": "f8ed7ee1-1d5c-48b5-b6c3-6a31e6fc"
        }
    },
    "rawTimestamp": "2022-11-12T12:57:45.1909085Z",
    "callerId": "urn:botframework:azure",
    "hashId": "5da0a5f4-0e83-4e9d-a1d5-2026b69"
}
```

Do you have any ideas how we can receive event only once?

**Comment by ramfattah** [comment] 2022-11-29 04:39
Might be related to https://github.com/microsoft/botbuilder-js/issues/4202
Fix #4203 was included in JavaScript SDK release [4.17.0](https://github.com/microsoft/botbuilder-js/releases#:~:text=fix%3A%20%5B%234202%5D%5Bbotbuilder%5D%20TeamsActivityHandler%20%E2%80%94%20Prevent%20calling%20event%20handlers%20twice%20by%20%40alexrecuenco%20in%20%234203).

@Serginyo90, could you please try to update the javascript botbuilder sdk to latest version?

**Comment by Serginyo90** [comment] 2022-11-29 15:44
@ramfattah I updated botbuilder and botbuilder-dialogs to 4.18.0 but issue still exists. 
The same behavior. Duplicated onMembersAdded event

**Comment by Serginyo90** [comment] 2022-11-29 15:47
here is example of code
`export default class TeamsActivityService extends TeamsActivityHandler {
  constructor() {
    super()

    this.onConversationUpdate(async (context: TurnContext, next) => {
      await this.addConversationReference(context)
      await next()
    })

    this.onMembersAdded(async (context: TurnContext, next) => {
      await this.addConversationReference(context)
      await next()
    })

    this.onMessage(async (context: TurnContext, next) => {
      await this.addConversationReference(context)
      await next()
    })

    // this.initConversations()
  }`

**Comment by ramfattah** [comment] 2022-12-07 01:53
Thanks for providing the code @Serginyo90, looking into this further.

**Comment by ramfattah** [comment] 2022-12-08 22:04
Thanks for your patience @Serginyo90,


I was able to repro this issue after installing bot sample [bot-conversation](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/nodejs) in Teams.

sharing the steps to repro:
1. Clone [bot-conversation/nodejs](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/nodejs)
2. Follow the readme to set up the bot with Teams 
3. In [bots/teamsConversationBot.js](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/nodejs/bots), change the `onMembersAddedActivity` method to the following:
    ```js
        this.onMembersAdded(async (context, next) => {
            await Promise.all((context.activity.membersAdded || []).map(async (member) => {
                if (member.id !== context.activity.recipient.id) {
                    await context.sendActivity(`Welcome to the team`);
                }
            }));

            await next();
        });
    ```
4. Run and add the bot app to Teams client. 
     <img src="https://user-images.githubusercontent.com/38049078/206571872-e5ae343c-f779-4794-8179-037fd5b96f35.png" width="300"/>
6. Notice the POST request in Ngrok after the bot has been installed and `onMembersAdded` event is triggered:
     <img src="https://user-images.githubusercontent.com/38049078/206574252-fbe901fa-63f6-4bcb-8a07-2a3807df661e.png" width="500"/>

**Comment by ramfattah** [comment] 2022-12-08 22:09
Hey @JuanAr,

I was able to repro this issue. Assigned this to you for now.

Please let me know if you have any questions. 
Thanks.

**Comment by erquirogasw** [comment] 2022-12-14 20:42
Hi @ramfattah .
We tried to reproduce the issue but we couldn't see the _onMembersAdded_ event triggered more than once.
Have you been able to see the event triggered two times? In the image you shared, we see it once with the ids of the user and the bot.

**Comment by ramfattah** [comment] 2022-12-19 17:55
Thanks for checking on this @erquirogasw, 

The above screenshot was taken right after the bot app was installed in Teams.
If a member was added to a group (not install), then the result looked like:
```json
    "membersAdded": [
        {
            "id": "xx:xxxxx...........................",
            "aadObjectId": "xxxxxxxx..........."
        }
    ],
```

While investigating this issue; so far, I've found that the `onMembersAdded` event gets triggered with the following scenarios:
1. If user joins a group chat 
2.  If user install the bot app in Teams

Scenario #1 was not reproducible, whereas scenario #2 is reproducible. 

```json
    "membersAdded": [
        {
            "id": "29:1Iat8W8y5w9RxIgqFnDUqJlJalpDXC5jlXWG3hYzfczu25fn_gNbbc6WV7V36GbpgvQjpt8_w5nHuW_os7d",
            "aadObjectId": "9272a828-5c43-4a1c-8a15-e315f8a8"
        },
        {
            "id": "28:331df719-bfd2-4fcc-aa91-f08bc21a"
        }
    ],
```

#

Please let me know if I've done something incorrectly or if you have any questions.
Thanks.

**Comment by Serginyo90** [comment] 2022-12-20 07:55
@ramfattah @erquirogasw main issue for me is I receive current event twice and sometime once. But usually twice. Did you able to reproduce it?
![Screenshot 2022-12-20 at 10 50 36](https://user-images.githubusercontent.com/20815176/208613320-6e39f5a1-44a0-4dab-9a3c-c8f0e92504ae.png)

**Comment by erquirogasw** [comment] 2022-12-21 17:05
Hi everyone, we couldn't reproduce the issue. If we install the app normally, we only receive the event once (with the two ids, user and bot, but that's expected).
We can see two MembersAdded events when we install the app in two different scopes (team and personal) as shown in the images.
@Serginyo90, can you give us more information? In which scope are you installing your bot (personal, team, meeting)? Do you have a sample bot to test this behavior?
Thanks!
![image (178)](https://user-images.githubusercontent.com/64815358/208962894-96e3c03f-b209-4f3c-b4e5-0d846703fc24.png)

**Comment by Serginyo90** [comment] 2022-12-22 16:57
@erquirogasw it is personal scope in both cases. 
![Screenshot 2022-12-22 at 19 54 18](https://user-images.githubusercontent.com/20815176/209186529-9ae3d886-c81a-4587-b4c2-d71410829ea3.png)
I see that you received 2 api calls each time when add app on your screenshot. But must be only one. Correct?
Does in 2nd one the same information like in first one?

**Comment by Serginyo90** [comment] 2022-12-25 07:43
@erquirogasw Ok. I will prepare the code and share with you on Tuesday

**Comment by Serginyo90** [comment] 2022-12-27 09:06
@erquirogasw You can find the sample bot here https://github.com/Serginyo90/issue-with-ms-bot .
P.S. I tried to reproduce it with Bot Framework Emulator but can't. Can you try reproduce with Azure Bot?

**Comment by erquirogasw** [comment] 2023-01-02 20:30
Hi @Serginyo90, we weren't able to reproduce the issue when installing the provided sample in Teams. We got the same outputs as before and the behavior seems to be the expected. The only difference we can think off is the app manifest. Could you share yours so we can compare and test it?

**Comment by ramfattah** [comment] 2023-01-23 01:16
Closing due to inactivity. @Serginyo90, please re-open if needed.

**Closed by ramfattah** 2023-01-23 01:16 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to

**Comment by Serginyo90** [comment] 2023-02-09 08:34
Sorry, I was in vacation guys. 
Sure... here is manifest
`{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.13/MicrosoftTeams.schema.json",
  "manifestVersion": "1.13",
  "version": "2.3.13",
  "id": "e1dc8cc5-....",
  "packageName": "com.microsoft.teams.extension",
  "developer": {
    "name": "Teams App, Inc.",
    "websiteUrl": "https://prohabits.com",
    "privacyUrl": "https://assets.stg.prohabits.com/mst/helpers/privacy.html",
    "termsOfUseUrl": "https://prohabits.com/how-it-works-2"
  },
  "icons": {
    "color": "resources/color.png",
    "outline": "resources/outline.png"
  },
  "name": {
    "short": "ProHabits Stg",
    "full": "ProHabits Stg Corporation"
  },
  "description": {
    "short": "ProHabits Stg is created for motivation",
    "full": "ProHabits Stg makes people better and better each day. We are here 24/7 to help you achieve your goals."
  },
  "accentColor": "#FFFFFF",
  "bots": [
    {
      "botId": "e1dc8cc5-8...",
      "scopes": ["personal", "team", "groupchat"],
      "supportsFiles": false,
      "isNotificationOnly": true
    }
  ],
  "composeExtensions": [],
  "configurableTabs": [
    {
      "configurationUrl": "https://assets.stg....",
      "canUpdateConfiguration": true,
      "scopes": ["team", "groupchat"]
    }
  ],
  "staticTabs": [
    {
      "entityId": "conversations",
      "scopes": ["personal"]
    },
    {
      "entityId": "dashboard",
      "name": "Community",
      "contentUrl": "https://assets.stg.prohabits.com/...#/dashboard",
      "websiteUrl": "https://assets.stg.prohabits.com/...#/dashboard",
      "scopes": ["personal"]
    },
    {
      "entityId": "myActivities",
      "name": "Progress",
      "contentUrl": "https://assets.stg.prohabits.com/...#/myActivities",
      "websiteUrl": "https://assets.stg.prohabits.com/...#/myActivities",
      "scopes": ["personal"]
    },
    {
      "entityId": "settings",
      "name": "Settings",
      "contentUrl": "https://assets.stg.prohabits.com/...#/settings",
      "websiteUrl": "https://assets.stg.prohabits.com/...#/settings",
      "scopes": ["personal"]
    },
    {
      "entityId": "leaderboard",
      "name": "Leaderboard",
      "contentUrl": "https://assets.stg.prohabits.com/...#/leaderboard",
      "websiteUrl": "https://assets.stg.prohabits.com/...#/leaderboard",
      "scopes": ["personal"]
    }
  ],
  "permissions": ["identity", "messageTeamMembers"],
  "validDomains": [
    "mabbly.wistia.com",
    "youtube.com",
    "youtu.be",
    "prohabits.com",
    "typeform.com",
    "assets.prohabits.com",
    "assets.dev.prohabits.com",
    "assets.stg.prohabits.com"
  ],
  "webApplicationInfo": {
    "id": "e1dc8cc5-....",
    "resource": "https://localhost:3000"
  },
  "activities": {
    "activityTypes": [
      {
        "type": "Daily MicroActivity",
        "description": "Morning Notification",
        "templateText": "{activityName}"
      }
    ]
  }
}
`

**Comment by erquirogasw** [comment] 2023-02-16 20:04
Hi @Serginyo90. We tested your manifest with the sample you provided both locally and in Azure, and the _membersAdded_ event was received only once.
Also, we connected the sample to Azure Application Insights to discard a problem with it, and we got only one event.
Do you have any other feature implemented that might be causing that behavior?
![image](https://user-images.githubusercontent.com/64815358/219474778-6430913a-723d-4cf2-910e-7fba6c3e7e4b.png)

**Comment by Serginyo90** [comment] 2023-02-17 09:41
@erquirogasw Ok. Looks like I found issue. Just want to confirm that it triggers onMembersAdded and onConversationUpdate events when user installs the App.

**Comment by Serginyo90** [comment] 2023-02-17 14:09
@erquirogasw so could you confirm that it triggers onMembersAdded and onConversationUpdate events when user installs the App, please?

**Comment by erquirogasw** [comment] 2023-02-17 14:41
Hi @Serginyo90. When installed, it triggers the _installationUpdate_ and _conversationUpdate_ (containing _membersAdded_ info) events.

![image (209)](https://user-images.githubusercontent.com/64815358/219684542-4478ad9b-26a3-44aa-b97c-5f91cda8f989.png)
![image (210)](https://user-images.githubusercontent.com/64815358/219684571-c5631ac0-796e-4d15-91e4-7daa25ef3674.png)

**Comment by Serginyo90** [comment] 2023-02-24 07:55
@erquirogasw thank you. I will rewrite logic using installationUpdate type.

**Comment by Serginyo90** [comment] 2023-02-28 08:01
@erquirogasw I can confirm that installationUpdate also triggered twice. The same like conversationUpdate. So issue still exists

**Comment by erquirogasw** [comment] 2023-03-06 15:30
Hi @ramfattah @Serginyo90 .
We weren't able to reproduce this issue in any of the following scenarios:

- Using the [bot-conversation](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/nodejs) sample. Locally and deployed to Azure.
- Using the provided [sample](https://github.com/Serginyo90/issue-with-ms-bot). Locally, deployed in Azure and with Application Insights.

In both scenarios, we could see 2 requests. One with activityType _installationUpdate_ and another with activityType _conversationUpdate_.
The _conversationUpdate_ contains the _membersAdded_ array with the data of the bot and the user.
Also, we tried installing the application as personal chat, meeting, and group.
@ramfattah should we re-open this issue to investigate further?
