### ISSUE TITLE
[SkillDialog] Bring forward skill dialog implementation to JS

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-js#1969] opened 2020-04-01 16:13 UTC
Tracking ticket to bring forward Skill dialog to JS.

**Comment by EricDahlvang** [comment] 2020-04-01 16:39
@vishwacsena Is this issue tracking something other than https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/skillDialog.ts ?

**Comment by vishwacsena** [comment] 2020-04-01 16:41
@EricDahlvang also need to bring forward adaptive pieces. Basically C# parity.

**Comment by clearab** [comment] 2020-04-03 21:23
Closing as duplicate of: https://github.com/microsoft/botbuilder-js/issues/1691

**Closed by clearab** 2020-04-03 21:23 UTC
Labels: R9, Skills
