### ISSUE TITLE
Port BotPreviewSend/Edit from C# to JS

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botbuilder-js#1238] opened 2019-10-01 22:16 UTC
https://github.com/microsoft/botbuilder-dotnet/pull/2637/files

**Comment by daveta** [comment] 2019-10-03 22:43
@Virtual-Josh : Renaming to reflect reality (link referenced).  There needs to be an additional bug files for the PreviewSendEdit.

**Comment by EricDahlvang** [comment] 2019-10-03 23:00
Closing as duplicate of https://github.com/microsoft/botbuilder-js/issues/1197  (in c# the ActionBasedMessagingExtension-FetchTask also includes the BotPreviewSend/Edit )

**Closed by EricDahlvang** 2019-10-03 23:00 UTC
Labels: 4.6, teams
