### ISSUE TITLE
[OAuthPrompt] The call to https://api.botframework.com/api/usertoken/GetToken returns a 500 response

### ISSUE THREAD

**Issue by elacallefactorial** [microsoft/botbuilder-js#4418] opened 2023-01-24 13:21 UTC
## Versions
4.16

## Describe the bug

When using the OAuthPrompt Dialog from the SDK, the call to https://api.botframework.com/api/usertoken/GetToken performed by the SDK returns a 500 status error response. According to the code, the SDK awaits either a 200 or 404 status.

## To Reproduce

I tried to follow this guide in order to add authentication to the bot with my own identity provider:

[https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp](url)

1. Configure a custom identity provider on Azure
2. Configure the bot with the identity provider connection name
3. Type anything
4. Auth Prompt should appear but nothing happens
5. I receive a 500 status code in the response
6. The bot console displays the following error:

```
      body: '{\r\n' +
        '  "error": {\r\n' +
        '    "code": "ServiceError",\r\n' +
        '    "message": "Error retrieving token: caeb276526109146868df38d74c9c52a."\r\n' +
        '  }\r\n' +
        '}',
```

## Expected behavior
Auth Prompt should display a sign-in button

**Comment by ramfattah** [comment] 2023-01-24 18:28
@elacallefactorial,

Tested NodeJS sample [18.bot-authentication](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/18.bot-authentication) with: 
* node v14.17.3
* "botbuilder": "~4.17.0"

Authentication seems to work as expected:
![image](https://user-images.githubusercontent.com/38049078/214373876-4844670e-050a-4363-9bac-f766f80ed7cc.png)

**Comment by ramfattah** [comment] 2023-01-24 18:33
@elacallefactorial,

* Perhaps there was an outage? Could you try again to see if it has been resolved? 
* Is this authentication issue specific to SDK 4.16? 
* What channel are you using?

**Comment by elacallefactorial** [comment] 2023-01-25 11:22
> @elacallefactorial,
> 
> * Perhaps there was an outage? Could you try again to see if it has been resolved?
> * Is this authentication issue specific to SDK 4.16?
> * What channel are you using?

Hi @ramfattah,

I think there is not an outage, I followed the same steps as you did before. I use the west Europe availability zone in Azure.
I'm not sure if this is an error specific to v4.16.
I'm using the Microsoft teams channel

I used this sample [18.bot-authentication](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/18.bot-authentication) now

node v16.16.0 
bot-builder 4.16
Generic OAuth 2
Multi-tenant application type


![Screenshot 2023-01-25 at 12 07 18](https://user-images.githubusercontent.com/107854088/214550408-33660122-56ed-466a-8dd1-f6ff9ddf3517.png)

**Comment by ramfattah** [comment] 2023-01-25 17:25
Hi @elacallefactorial,



Tested in Teams channel using sample [46.teams-auth](https://github.com/microsoft/BotBuilder-Samples/tree/main/archive/samples/javascript_nodejs/46.teams-auth). 
I'm not able to reproduce this issue with Generic OAuth2 identity provider.

Followed [OAuth generic providers](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-concept-identity-providers?view=azure-bot-service-4.0&tabs=adv2%2Cga2#oauth-generic-providers) (Generic OAuth2) documentation to setup oauth connection in azure bot:
<html>
<body>


Property | Description or value
-- | --
Name | A name for this identity provider connection.
Service Provider | The identity provider to use. Select Generic Oauth 2.
Client id | Your client ID obtained from the identity provider.
Client secret | Your client secret obtained from the identity provider registration.
Authorization URL | https://login.microsoftonline.com/common/oauth2/v2.0/authorize
Token URL | https://login.microsoftonline.com/common/oauth2/v2.0/token
Refresh URL | https://login.microsoftonline.com/common/oauth2/v2.0/token
Token Exchange URL | Leave this empty if not sso.
Scopes | A comma-separated list of the API permissions you granted to the identity provider app. Example, `openid`


</body>
</html>

![image](https://user-images.githubusercontent.com/38049078/214635358-25576235-6a21-40f8-b164-d6942c587cab.png)

![image](https://user-images.githubusercontent.com/38049078/214635421-99418428-cb0c-4104-b51f-59ce2e260456.png)


manifest.json:
```json
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.14/MicrosoftTeams.schema.json",
  "manifestVersion": "1.14",
  "version": "1.0.0",
  "id": "57.......3c",
  "packageName": "com.microsoft.teams.samples",
  "developer": {
    "name": "Microsoft",
    "websiteUrl": "https://example.azurewebsites.net",
    "privacyUrl": "https://example.azurewebsites.net/privacy",
    "termsOfUseUrl": "https://example.azurewebsites.net/termsofuse"
  },
  "icons": {
    "color": "icon-color.png",
    "outline": "icon-outline.png"
  },
  "name": {
    "short": "Team Auth Module",
    "full": "Simple Team Auth Module"
  },
  "description": {
    "short": "Test Team Auth Module Scenario",
    "full": "Simple Team Auth Module Scenario Test"
  },
  "accentColor": "#FFFFFF",
  "bots": [
    {
      "botId": "57.......3c",
      "scopes": [
        "personal"
      ],
      "isNotificationOnly": false,
      "supportsCalling": false,
      "supportsVideo": false,
      "supportsFiles": false
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "token.botframework.com",
    "*.ngrok.io"
  ]
}
```

**Comment by elacallefactorial** [comment] 2023-02-03 16:02
Hi @ramfattah 

I followed the same steps, I tested with Bot emulator and Teams client and I still receive the same error message

![Screenshot 2023-02-03 at 16 55 52](https://user-images.githubusercontent.com/107854088/216648837-2bff009b-15cf-475b-82d1-cb6b0a0e613f.png)
![Screenshot 2023-02-03 at 16 40 13](https://user-images.githubusercontent.com/107854088/216648855-307faa02-00ed-444a-acb8-585251fcc359.png)

**Comment by elacallefactorial** [comment] 2023-02-07 16:17
Hi @ramfattah,

Can you tell me if it is possible to send you the OAuth connection parameters that I use by email in order to check it in your environment? I would like to have feedback about this error, to know where the issue is.

Greetings!

**Comment by ramfattah** [comment] 2023-02-07 16:37
That would be great, thank you @elacallefactorial.
If preferred, you can send it to my email at `v-fattahram@microsoft.com` and I will test from my environment.

Looking forward to your message.

**Comment by elacallefactorial** [comment] 2023-02-08 15:59
> That would be great, thank you @elacallefactorial. If preferred, you can send it to my email at `v-fattahram@microsoft.com` and I will test from my environment.
> 
> Looking forward to your message.

Hi @ramfattah 

I've already sent you the email. 

I look forward to receiving your update.

**Comment by ramfattah** [comment] 2023-02-09 16:42
Thanks @elacallefactorial, I confirm I've received the Email. 

Will report back soon.

**Comment by ramfattah** [comment] 2023-02-09 22:13
@elacallefactorial, 

Could you please verify if the OAuth works in Azure Bot "Test Connection"?

![image](https://user-images.githubusercontent.com/38049078/217950683-fbf5796d-ee76-4842-b307-55b5c2a5ec0d.png)

**Comment by elacallefactorial** [comment] 2023-02-10 08:52
> @elacallefactorial,
> 
> Could you please verify if the OAuth works in Azure Bot "Test Connection"?
> 
> ![image](https://user-images.githubusercontent.com/38049078/217950683-fbf5796d-ee76-4842-b307-55b5c2a5ec0d.png)

Hi

**Comment by elacallefactorial** [comment] 2023-02-10 08:53
> @elacallefactorial,
> 
> Could you please verify if the OAuth works in Azure Bot "Test Connection"?
> 
> ![image](https://user-images.githubusercontent.com/38049078/217950683-fbf5796d-ee76-4842-b307-55b5c2a5ec0d.png)

Hi @ramfattah,

The connection is working on Azure.

**Comment by elacallefactorial** [comment] 2023-02-13 14:46
> > @elacallefactorial,
> > Could you please verify if the OAuth works in Azure Bot "Test Connection"?
> > ![image](https://user-images.githubusercontent.com/38049078/217950683-fbf5796d-ee76-4842-b307-55b5c2a5ec0d.png)
> 
> Hi @ramfattah,
> 
> The connection is working on Azure.

I use an Azure bot from the Europe West region

**Comment by ramfattah** [comment] 2023-02-14 21:19
Thanks for your patience @elacallefactorial.

I'm able to reproduce this issue using **Azure Bot Europe West region** and bot sample [18.bot-authentication](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/18.bot-authentication) (Tested in WebChat). 
Followed this doc [Add authentication to a bot](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp) with Europe Data residency [OAuth Redirect URL](https://learn.microsoft.com/en-us/azure/bot-service/ref-oauth-redirect-urls?view=azure-bot-service-4.0).

Steps to reproduce:
1. Create an Azure Bot in West Europe Region
2. Add Authentication to the azure bot by following this [documentation](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp)
   1. For the Redirect URI, select Web and set the URL `https://europe.token.botframework.com/.auth/web/redirect`
   2. Used AAD2 Identity 
3. Configure sample [18.bot-authentication](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/18.bot-authentication) with OAuth connection name, msft app id, and msft password.
4. Run the bot locally and test OAuth connection in the bot.

![image](https://user-images.githubusercontent.com/38049078/218864441-a900536c-5d16-4a18-8e0f-b281b4755ec4.png)

**Comment by ramfattah** [comment] 2023-02-15 04:20
Discussing with the engineering team for next steps.

Thanks @elacallefactorial.

**Comment by elacallefactorial** [comment] 2023-02-16 15:55
> Discussing with the engineering team for next steps.
> 
> Thanks @elacallefactorial.

Great, thank you again and I look forward to your answer.

**Comment by ramfattah** [comment] 2023-02-20 19:37
Hi @elacallefactorial, thanks for your patience.

Looks like there may be additional configurations needed for West Europe region.

Could you please provide below additional configuration in `.env` file and try again to see if that fixes this authentication issue:
```ini
BotOpenIdMetadata=https://login.botframework.com/v1/.well-known/openidconfiguration
ValidateAuthority=true
ToChannelFromBotLoginUrl=https://login.microsoftonline.com/botframework.com
ToChannelFromBotOAuthScope=https://api.botframework.com
ToBotFromChannelTokenIssuer=https://api.botframework.com
OAuthApiEndpoint=https://europe.api.botframework.com
ToBotFromChannelOpenIdMetadataUrl=https://login.botframework.com/v1/.well-known/openidconfiguration
ToBotFromEmulatorOpenIdMetadataUrl=https://login.microsoftonline.com/botframework.com/v2.0/.well-known/openid-configuration
CallerId=urn:botframework:azure
```

Example:
![image](https://user-images.githubusercontent.com/38049078/220186237-3ca67731-7bb7-4129-af18-34b23e941a50.png)

Let me know if you have any questions.
Thanks.

**Comment by johnataylor** [comment] 2023-03-03 19:06
The configuration provided should resolve this issue. Closing. Please reopen if you continue to have problems. Thanks.

**Closed by johnataylor** 2023-03-03 19:06 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to

**Comment by elacallefactorial** [comment] 2023-03-23 22:03
It's working. On the other hand, How can we retrieve the connection access token to use it in a Microsoft Teams tab?
