### ISSUE TITLE
Upgrade CosmosDB SDK to the latest release

### ISSUE THREAD

**Issue by sgellock** [microsoft/botbuilder-js#328] opened 2018-08-15 15:39 UTC
CosmosDB has a new release of their SDK for NodeJS.  We should consider pulling this in before code-complete, for the v4 release

**Comment by v-ducvo** [comment] 2018-09-06 20:17
Hi...I filed and issue relating to CosmosDb here:
https://github.com/Microsoft/botbuilder-js/issues/403

Can someone test to make sure it does not reproduce in this release/version? Thanks.

**Comment by stevengum** [comment] 2018-09-16 19:13
Right now we're snapped to 1.14.5 [which is the latest release](https://www.npmjs.com/package/documentdb), and post-Ignite we will update to the latest release when a new SDK is released.

**Comment by iMicknl** [comment] 2018-09-16 19:35
The new SDK is already released (and it is awesome!). 1.14.5 is the latest release of `documentdb`, however it recently got rebranded to [`@azure/cosmos`](https://www.npmjs.com/package/@azure/cosmos) which is on version 2.0.0-4 now.

**Comment by carlosscastro** [comment] 2018-09-16 20:52
Thanks @iMicknl!!! Is the surface API the same or is it substantially different? We are code complete tonight, so we might have to take that for a next release in a few weeks.

**Comment by iMicknl** [comment] 2018-09-16 21:07
You can read more about the new [Azure CosmosDB JavasScript SDK here](https://azure.microsoft.com/en-us/blog/new-azure-cosmosdb-javascript-sdk-2-0-now-in-public-preview/), still in public preview by the way. Note that they dropped Node 4 support, I am not sure what BotBuilder SDK v4 supports?

I don't know if the surface API is totally different, as far as I know the biggest change is the support for promises and renaming of the models.

**Comment by stevengum** [comment] 2018-09-16 21:15
Hooray for Promises! ([Their note about Node 4 support](https://github.com/Azure/azure-cosmos-js#prerequisites))

If users are on the current Node LTS (8.12.0) they will definitely be able to use the v4 SDK.

**Comment by daveta** [comment] 2018-10-30 20:46
We are up to date on Cosmos for v4.1.

Apparently there's a new library just released in the past week+.

**Comment by johnataylor** [comment] 2018-11-20 06:53
We are on the latest version of the documentdb package 1.14.5 last published 4 months ago.

However, there is a new CosmosDB package in npmjs under a different name [@azure/cosmos](https://www.npmjs.com/package/@azure/cosmos) this was published 13days ago.

Presumably we should switch to that package. This will, however, require some code change. The concepts remain the same and an initial look at the API change suggests the changes will be relatively minor.

**Comment by johnataylor** [comment] 2018-11-20 18:42
per conversation with @sgellock moving this to next milestone.

**Comment by johnataylor** [comment] 2019-01-29 23:10
We should be moving to the Azure/* packages. However, they imply a major rev of our implementation as the code can be quite different now. In addition these new packages are essential v1 for the new client. The documentation and samples are not all there. Moving this to the next milestone. (We also want to do more significant work around state in the next milestone too.)

**Comment by mdrichardson** [comment] 2019-01-30 15:58
I've got [a working implementation](https://github.com/mdrichardson/botbuilder-js/blob/cosmosPull/libraries/botbuilder-azure/src/cosmosDbStorage.ts) in Node with written and passing tests. It was 90% written before I came across the above design guidelines, but I think it still matches the intent. I'm hoping to get to a dotnet/C# version, but I'm still new to C# and am busy working on support tickets, so somebody else might be able to implement faster than I.

**Comment by mdrichardson** [comment] 2019-01-30 17:32
@stevengum I spoke with @cleemullins about this a week or so ago and his guidance was more or less to have a C# version ready first. I posted this here (and elsewhere) just to make sure it was visible to you guys so we don't need to duplicate effort.

I can still open a PR, if you'd like.

**Comment by stevengum** [comment] 2019-01-30 17:38
If that was his guidance, let's hold off on the PRs for now until a matching implementation is done in C#. @cleemullins and @johnataylor will have stronger opinions on the final implementation, and maybe @daveta can chime in as well. Thanks for the heads up and initiative!

**Comment by stevengum** [comment] 2019-01-30 17:59
@mdrichardson, I took a _very_ cursory glance at your branch and one thing that stood out is the following code under [`CosmosDbStorage.delete()`](https://github.com/mdrichardson/botbuilder-js/blob/c6e00b989fcfe030ddf9c92d1711d81a965fb8f7/libraries/botbuilder-azure/src/cosmosDbStorage.ts#L279-L284):

```ts
        await keys.map(async (k: string) => {
            try {
                const reqOptions = { partitionKey: this.settings.partitionValue };
                await this.container
                    .item(CosmosDbKeyEscape.escapeKey(k), this.settings.partitionKey)
                    .delete(reqOptions);
            } catch (err) {
                // Don't thow an error if trying to delete something that doesn't exist
                if (err.code !== 404) {
                    throw new Error(`Unable to delete document: ${JSON.stringify(err)}`);
                }
            }
        });
```

This doesn't seem like the right behavior; if the document doesn't exist, then the bot's key is incorrect. If one delete fails due to an incorrect key, that might be a transient blip; but if all of the deletes fail due to missing documents then that's a problem. One of the more likely problems being that the keys the bot is formulating are incorrect. The bot's developer should have these errors be exposed to them and they can decide how they want to proceed.

There's also a small typo in the comment 😄

**Comment by mdrichardson** [comment] 2019-01-30 18:02
@stevengum That's a good catch. I'll look over it and do some more testing. While I was trying to get the partitionKey/partitionValue system figured out, I recall I'd see documents be deleted and still get a 404 error. Now that I've got the key/value figured out, I'll do some testing and commit/push if a change is needed.

**Comment by mdrichardson** [comment] 2019-01-30 23:31
@stevengum 

I found out why I originally didn't throw for the 404 errors on delete. The [current tests say it shouldn't throw](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-azure/tests/cosmosDbStorage.test.js#L174) and the [current implementation doesn't throw](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-azure/src/cosmosDbStorage.ts#L241), either. I think your reasoning is sound, so I added `console.log()` messages for when this happens. But would we expect this to happen during use? I tested a couple of bots and never had the message show, but I'd guess that if the current implementation wasn't supposed to throw, there was a reason. What do you think?

**Comment by mdrichardson** [comment] 2019-02-05 21:53
Related: https://github.com/Microsoft/BotBuilder/issues/5107

**Comment by cleemullins** [comment] 2019-04-13 00:58
@mdrichardson Can you share what we should do with this? Do you have PR's ready? I would love to either:
1. Get onto the latest packages and close this issue.
2. Punt this to 4.5, at which point we do that same work. 

My preference is #2, as we have significant samples and other doc changes in flight for this cycle and the change now may impact that.

**Comment by mdrichardson** [comment] 2019-04-15 14:54
@cleemullins I had a JS version ready to go, but we've made enough changes to `CosmosDbStorage` that I'll need to re-look at it. The `@azure/cosmos` module is a pretty big change from `DocumentDb`, which is what we currently use. As such, I recommend we don't upgrade until the C# Cosmos SDK is ready, to ensure parity. Last I looked, the C# Cosmos SDK V3 (the new one) didn't allow non-partitioned DBs, which breaks backwards-compatibility. I'll take another look, but I don't believe it's ready.

There's some partitionKey things that we may as well handle when we make this change, too. I sent a Design Proposal for it that could use your review. Let me know if you didn't receive it.

**Comment by mdrichardson** [comment] 2019-05-10 14:40
@cleemullins Update: C# Cosmos SDK V3 team has an actual task, now, to [make PartitionKey optional](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/230) (for backwards compatibility. That SDK is still in preview. Looks like [GA is planned for first half of 2019 still](https://github.com/Azure/azure-cosmos-dotnet-v3/projects), so we might be able to update to the new SDKs in the next couple of months.

**Comment by mdrichardson** [comment] 2019-06-03 15:14
@cleemullins The C# Cosmos SDK V3 is [pretty close to GA](https://github.com/Azure/azure-cosmos-dotnet-v3/projects/2) now and I believe PartitionKey is optional (backwards-compat achieved). I can start working on the updates, if you'd like.

**Comment by sgellock** [comment] 2019-06-21 20:17
introduces breaking changes

**Comment by Stevenic** [comment] 2020-01-30 23:04
Closed as wontfix

**Closed by Stevenic** 2020-01-30 23:04 UTC
Labels: WontFix, approved, backlog, enhancement

**Comment by christopheranderson** [comment] 2020-01-31 00:54
Just an update, this was done and is implemented here: https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-azure/src/cosmosDbPartitionedStorage.ts

So we now support old way on `documentdb` package and new way on `@azure/cosmos` package.
