### ISSUE TITLE
[Feature Request] Update azure-storage-js to v10

### ISSUE THREAD

**Issue by GasparAcevedoZainSouthworks** [Microsoft/botbuilder-js#706] opened 2018-12-27 21:01 UTC
A new version of `azure/storage-js` ([v10.3.0](https://github.com/Azure/azure-storage-js)) has been published with major changes. The project actually uses the [`2.10.2`](https://github.com/azure/azure-storage-node#microsoft-azure-storage-sdk-for-nodejs-and-javascript-for-browsers) version, which differences with the new one are that it has only one package which includes the implementation of `blob`, `queue` and `file` storage, but the `v10.3.0` has a different package for each one.
Also, the project only uses the `blob-storage` implementation, so it would be more performant to only use the respective package ([`Azure/storage-blob`](https://github.com/Azure/azure-storage-js/tree/master/blob)).

**Note**
The `Azure/storage-blob` is the only package of the new version which is not in preview stage

**Comment by johnataylor** [comment] 2019-01-29 22:38
The Azure/* packages are a complete API change. They are essentially v1 of a new client. There is no urgency to jump on this for this milestone. Moving to 4.4.

**Comment by cleemullins** [comment] 2019-04-13 01:03
Duplicate of #328. Closing.

**Closed by cleemullins** 2019-04-13 01:03 UTC
Labels: 4.4, Approved, P1
