### ISSUE TITLE
cosmosDbStorage fails to delete

### ISSUE THREAD

**Issue by galenguilbert** [microsoft/botbuilder-js#1189] opened 2019-09-20 13:07 UTC
## Versions
What package version of the SDK are you using. 4.4.0
What nodejs version are you using 10.14.1
What browser version are you using na
What os are you using linux

## Describe the bug
cosmosDbStorage is able to create and read documents, but cannot delete them.  It consistently returns an error.

"The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection."

## To Reproduce
1. Create a new instance of CosmosDbStorage named "storage"
2. Perform a storage.write - success
3. Perform a storage.read - success
4. Pefrom a storage.delete - fail with this error

> "{\"code\":\"BadRequest\",\"message\":\"Message: {\\\"Errors\\\":[\\\"The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.\\\"]}\\r\\nActivityId: 0f36d51e-74cf-4825-8e30-9ddd616fb3b4, Request URI: /apps/2d232d7f-3916-44d9-ada4-df3c55c2d8c4/services/1d6802d8-8183-4c62-8b55-5661ad10e2fc/partitions/ca76959e-55fb-4ccd-afd1-464fb6e6e909/replicas/132127020915794086p/, RequestStats: \\r\\nRequestStartTime: 2019-09-20T12:38:46.5800126Z, RequestEndTime: 2019-09-20T12:38:46.5900179Z, Number of regions attempted: 1\\r\\nResponseTime: 2019-09-20T12:38:46.5900179Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-eastus1-fd3.documents.azure.com:16832/apps/2d232d7f-3916-44d9-ada4-df3c55c2d8c4/services/1d6802d8-8183-4c62-8b55-5661ad10e2fc/partitions/ca76959e-55fb-4ccd-afd1-464fb6e6e909/replicas/132127020915794086p/, LSN: 186, GlobalCommittedLsn: 186, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 1001, RequestCharge: 0, ItemLSN: -1, SessionToken: 186, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Delete\\r\\n, SDK: Microsoft.Azure.Documents.Common/2.5.1\"}"

## Expected behavior
Deletion functions properly

## Screenshots
<img width="1189" alt="Screen Shot 2019-09-20 at 7 02 22 AM" src="https://user-images.githubusercontent.com/39504713/65328961-c176fa00-db74-11e9-8d55-aa0a70798607.png">

## Additional context
The botstate-collection container has a partition key of /id - If I add that partition key to the CosmosDbStorageSettings, I don't get the error, but instead just a 404 key not found.

[bug]

**Comment by mdrichardson** [comment] 2019-09-20 17:26
I'm going to close this as it's a duplicate of [a known issue](https://github.com/microsoft/botframework-sdk/issues/5467)

That thread contains a few different workarounds. All of them work, but I'd recommend the one under the "Update" heading. If you run into trouble, please post on that issue.

**Closed by mdrichardson** 2019-09-20 17:26 UTC
Labels: Bot Services, customer-reported
