### ISSUE TITLE
[BotBuilder] TeamsActivityHandler class does not match C# counterpart

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-js#3088] opened 2020-11-24 15:31 UTC
## Versions
What package version of the SDK are you using.
[botbuilder@4.11.0](https://www.npmjs.com/package/botbuilder/v/4.11.0)
What nodejs version are you using
[12.16.1](https://nodejs.org/en/blog/release/v12.16.1/)
What browser version are you using
\-
What os are you using
Windows 10 Pro

## Describe the bug
Give a clear and concise description of what the bug is.
The JavaScript implementation of `TeamsActivityHandler` contains different method's signatures compared to C#.

The methods in JavaScript uses the prefix `handle` while C# uses `on`.

## To Reproduce
1. Clone [BotBuilder-DotNet](https://github.com/microsoft/botbuilder-dotnet)
1. Navigate to `/libraries/Microsoft.Bot.Builder/Teams/`
1. Open `TeamsActivityHandler.cs`
1. Scroll down to [line 116](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L116)
1. Clone [BotBuilder-JS](https://github.com/microsoft/botbuilder-js)
1. Navigate to `/libraries/botbuilder/src/`
1. Open `teamsActivityHandler.ts`
1. Scroll down to [line 221](https://github.com/microsoft/botbuilder-js/blob/main/libraries/botbuilder/src/teamsActivityHandler.ts#L221)
1. See the differences

More differences are present between the files.

## Expected behavior
Give a clear and concise description of what you expected to happen.
I expect `TeamsActivityHandler` in JavaScript to use the same implementation as in C#.

## Screenshots
_Disparity in the `onSignInInvoke` method between C# and JavaScript_
![image](https://user-images.githubusercontent.com/11904023/100113957-a924fe00-2e4f-11eb-9ce9-f1e08a386f2a.png)

_`handleTeamsSignInVerifyState` vs `OnTeamsSignInVerifyStateAsync`_
![image](https://user-images.githubusercontent.com/11904023/100113960-ab875800-2e4f-11eb-84bc-39e6c18daaff.png)

_`handleTeamsO365ConnectorCardAction` vs `OnTeamsO365ConnectorCardActionAsync`_
![image](https://user-images.githubusercontent.com/11904023/100113973-ade9b200-2e4f-11eb-90ed-2c9b4736ecb0.png)

## Additional context
C# Virtual Assistant overrides the [OnTeamsSignInVerifyStateAsync](https://github.com/microsoft/botframework-solutions/blob/master/samples/csharp/assistants/virtual-assistant/VirtualAssistantSample/Bots/DefaultActivityHandler.cs#L81) method while TypeScript Virtual Assistant overrides the [handleTeamsSignInVerifyState](https://github.com/microsoft/botframework-solutions/pull/3584/files#diff-7405c18d741c368604255a6cc1dfa7b17e67d29e1bb14aedbfc344992f2210cfR88) method.

**Comment by stevengum** [comment] 2020-12-02 01:12
Thanks for filing this @Batta32! This is by design, the initial ActivityHandler implementations in .NET and TypeScript differed to try and address a lack of idiomaticness perceived in TypeScript. This difference manifested in the event listener-derived TypeScript implementation shipped in 4.3:

https://github.com/microsoft/botbuilder-js/blob/c9b4001112d7dc428fcbb8f3629b481af73a8cec/libraries/botbuilder-core/src/activityHandler.ts#L65-L66

Whereas the .NET implementation followed a classic inheritance pattern through [public virtual](https://github.com/microsoft/botbuilder-dotnet/blob/867ec4780022674f50cfb721d95ea29a581fca6a/libraries/Microsoft.Bot.Builder/ActivityHandler.cs#L30-L61) methods.

```cs
public virtual Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
```

In botbuilder-js, the [`ActivityHandlerBase`](https://github.com/microsoft/botbuilder-js/blob/25efacda53e1bc46666b5289f7b0e1181152c421/libraries/botbuilder-core/src/activityHandlerBase.ts#L49-L68) class added in 4.6.0 matches the implementation of the 4.3.0 .NET ActivityHandler. This was added to better support Invoke activity handling for Teams. For Invoke Activities the bot must respond with a single InvokeResponse. This is normally returned by the buisness logic in the bot.

To avoid breaking changes, the method names are changed in TypeScript.

### For ActivityHandler methods:
- `on<ActivityType>Activity` represents the inheritance model (first defined in ActivityHandlerBase)
- `on<ActivityType>` represents the event listener pattern

### For TeamsActivityHandler methods:
- `onTeams*Event` represents the event listener pattern for Teams ConversationUpdates
- `onTeams*` represents the inheritance model for Teams ConversationUpdates
- `handleTeams*` is used to handle Teams Invoke Activities

 In .NET it was simple to plumb this through as they were already using an inheritance-based model, but for TypeScript the underlying ActivityHandler class needed to be reimplemented without breaking changes, which is why we have `handleTeams*()` in TS but `OnTeams*()` in .NET. 

___

To mirror the .NET VA implementation, one path would be subclassing the TeamsActivityHandler and then overriding and consuming the following methods (mentioned above):
- `on<ActivityType>Activity` represents the inheritance model (first defined in ActivityHandlerBase)
- `onTeams*` represents the inheritance model for Teams ConversationUpdates
- `handleTeams*` is used to handle Teams Invoke Activities

**Comment by Batta32** [comment] 2020-12-02 14:35
Awesome @stevengum, thank you for the provided information.

We already applied that approach in the microsoft/botframework-solutions#3584 for 1.0 TypeScript Virtual Assistant (see [DefaultActivityHandler](https://github.com/microsoft/botframework-solutions/pull/3584/files#diff-7405c18d741c368604255a6cc1dfa7b17e67d29e1bb14aedbfc344992f2210cf)).

If this is by design, feel free to close this issue 😊.

**Comment by stevengum** [comment] 2020-12-02 15:20
Great! Closing issue as the implementation differences are by design.

**Closed by stevengum** 2020-12-02 15:20 UTC
Labels: Area: SDK, ExemptFromDailyDRIReport, P2, Size: M, backlog, parity
