### ISSUE TITLE
OAuth card text being applied as card title 

### ISSUE THREAD

**Issue by isweetland** [microsoft/botbuilder-js#4319] opened 2022-09-02 17:07 UTC
## Versions
What package version of the SDK are you using. `4.17.0`
What nodejs version are you using `18.6`
What browser version are you using `Firefox 104.0`
What os are you using `macOs 12.3`

## Describe the bug

Cards created with `this.addDialog(new OAuthPrompt(...))` are having their card text applied as card title on **desktop**, **web** versions teams channels. This is resulting in text being cut off as it's limited to two lines. 

Cards are being rendered as expected on **mobile**. 

## To Reproduce
1. Create an OAuth Card using `OAuthPrompt` from `botbuilder-dialogs`
2. send this dialog in a Team channel using the web or desktop app
3. Notice that the `text` passed to the `OAuthPrompt` is being rendered as the hero card's `title`

## Expected behavior

It's expected that the `OAuthPrompt` text will be rendered as the card's text, not the title. 

## Screenshots

<img width="1292" alt="Screen Shot 2022-09-02 at 11 31 54 AM" src="https://user-images.githubusercontent.com/52611006/188199687-e3d92a55-d6c9-47d1-bd2d-418265aa2f45.png">

This is generated by the following `OAuthPrompt`:

```js
this.addDialog(
    new OAuthPrompt('OAuthPrompt', {
        connectionName: ConnectionName,
        text: 'You will be prompted to authenticate with your identity provider',
        title: 'Log In & Authorize'
    }),
);
```

Note the `text` string is being applied as `class="card-title"`

## Additional context

* In one-on-one conversations the cards are being rendered correctly (although the card text is **bold** it's not being cut off).
* In all chats on mobile the cards are being rendered correctly.

**Comment by ramfattah** [comment] 2022-09-06 17:59
Thanks @isweetland, we are investigating.

**Comment by ramfattah** [comment] 2022-09-07 23:57
Hi @isweetland, 

I was able to repro, looks like in the Teams channel, the [text](https://github.com/microsoft/botbuilder-js/issues/4319#:~:text=text%3A%20%27You%20will%20be%20prompted%20to%20authenticate%20with%20your%20identity%20provider%27%2C) is displayed more like a title.
Tested using sample [46.teams-auth](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/46.teams-auth) and added [AAD v2 OAuth Connection](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp#create-the-azure-ad-identity-provider).

Sharing screenshots for comparison.

Teams:
![image](https://user-images.githubusercontent.com/38049078/189001397-02f424a6-efdc-4ea4-8e26-2648383c8398.png)


WebChat:
![image](https://user-images.githubusercontent.com/38049078/189001675-313a29ac-8f47-46ea-a9bd-3ec5b9428a15.png)

**Comment by ramfattah** [comment] 2022-09-07 23:58
The same behavior occurs with C# samples.
We will check with the engineers on this and report back soon.

Thanks.

**Comment by ramfattah** [comment] 2022-09-08 23:05
Hi @JuanAr, this issue is reproducible.

In Teams channel, the OAuthPrompt text font is bold and rendered as a title.

**Comment by ceciliaavila** [comment] 2022-09-15 15:47
Hi everyone,
We reproduced the issue on Teams, and as mentioned, the card is shown correctly in 1-1 conversations while, in a Teams channel, the text is cut off.
BotBuilder-JS is sending the OAuth card correctly. It's _Teams_ who renders the card in different ways depending on the conversation type.

Here we can see the different structures and classes used in the two chats.
![image](https://user-images.githubusercontent.com/44245136/190448884-9fe00e33-c333-4766-b638-1ead25a21808.png)

**Comment by tdurnford** [comment] 2022-09-29 18:05
Closing as this channel specific behavior.

**Closed by tdurnford** 2022-09-29 18:05 UTC
Labels: bug, customer-reported, Bot Services, customer-replied-to, needs-triage
