### ISSUE TITLE
DialogContext.cancelAllDialogs() cannot cancel past ComponentDialog.

### ISSUE THREAD

**Issue by NicovdijkWork** [microsoft/botbuilder-js#866] opened 2019-04-08 19:22 UTC
## Versions
Versions of the library:
        "botbuilder": "4.3.2",
        "botbuilder-ai": "4.3.2",
        "botbuilder-azure": "4.3.4",
        "botbuilder-dialogs": "4.3.2"
Nodejs: v10.14.1
Windows

## Describe the bug
The dialog stack inside a `ComponentDialog` is reset. This causes the behavior that `DialogContext.cancelAllDialogs()` will only cancel all dialogs inside the `ComponentDialog`, but not any dialogs that are parent to the `ComponentDialog`. For me this was vey confusing. It took me quite some time to understand why not all dialogs were canceled. I don't know if this behavior is intended or necessary, but I did not read anything in the documentation about it.

## Expected behavior
When using `DialogContext.cancelAllDialogs()` I would expect all dialogs to be canceled irregardless of whether some are `ComponentDialog`s or not.

[bug]

**Comment by sgellock** [comment] 2019-04-08 20:42
@stevenic, by design?

**Comment by Stevenic** [comment] 2019-04-11 22:15
I've fixed this in 4.5. I think it would be relatively straightforward to apply that fix to 4.4.

**Comment by cleemullins** [comment] 2019-04-13 01:08
I believe we should not take this in 4.4. IT's a behavior change, a docs change, and (probably) samples change.

**Comment by NicovdijkWork** [comment] 2019-04-13 08:59
For anyone reading this, the work-around I used is to only use a single ComponentDialog at the root (like main conversation directions. All other dialogs (Prompts or WaterfallDialogs) that can end up on top of the ComponentDialog can be added to the DialogSet in the ActivityHandler instead. For instance, I have a cancel dialog and a corresponding ConfirmPrompt added to the DialogSet separately.

**Comment by mrestorff** [comment] 2019-08-07 11:57
Is there an update on this?

Just to double down on the issue, we're using a skill dispatch model similar to the Virtual Assistant template where each skill has its own dispatcher. This is complicating things massively when using that 1st level dispatcher dialog that in turn calls multiple ComponentDialog's (effectively 2nd level dispatcher's) which are used to handle the dialogs for each skill. The option to cancel the dialog stack completely would be great.

Would it be an option to add a seperate option for that and keep the current `cancelAllDialogs()` to not make any breaking changes?

**Comment by darrenj** [comment] 2019-08-14 11:01
Hi - Just catching up on this thread. Just to clarify - each Skill added to a Bot adds a new "target" to the Dispatcher model - an intent. This is used to identify if a question should be handed off to a (remote) skill.  We don't have separate dispatch models for each skill?

**Comment by sgellock** [comment] 2019-08-14 13:24
@NicovdijkWork we have addressed in the latest 4.5 release.  If you can't move to 4.5 and need a solution, we can discuss further

**Closed by sgellock** 2019-08-14 13:24 UTC
Labels: 4.6, P1, bug
