### ISSUE TITLE
[PORT] Update TelemetryClient to enable tracking of dialog ('page') views

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1844] opened 2020-03-04 21:06 UTC
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3440

Addresses #3441 

Update TelemetryClient to enable tracking of page views and add automatic page view logging on dialog start for component / waterfall dialogs.

~~This PR now adds a new abstract class, ***LogTelemetryClient***, as well as an implementation of it within the ApplicationInsights library, ***AppInsightsTelemetryClient***. All current consumers of the existing ***BotTelemetryClient*** have been updated to use the new client, but leaving the existing functionality in place (marked as obselete) for backwards compatibility.~~

# Changed projects
* Microsoft.Bot.Builder.ApplicationInsights
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder
* integration
* Microsoft.Bot.Builder.ApplicationInsights.Tests
* Microsoft.Bot.Builder.Dialogs.Tests

**Comment by garypretty** [comment] 2020-03-05 17:49
Closing - duplicate of #1792

**Closed by garypretty** 2020-03-05 17:49 UTC
