### ISSUE TITLE
TypeScript error with latest packages

### ISSUE THREAD

**Issue by billba** [Microsoft/botbuilder-js#142] opened 2018-03-23 13:14 UTC
When compiling a (simple!) bot using botbuilder version `4.0.0-m2.1` I get:

```
node_modules/botframework-connector/lib/auth/channelValidation.d.ts(8,31): error TS7016: Could not find a declaration file for module 'jsonwebtoken'. '/Users/bill/Dropbox/billba-mbp/botbldr/node_modules/jsonwebtoken/index.js' implicitly has an 'any' type.
  Try `npm install @types/jsonwebtoken` if it exists or add a new declaration (.d.ts) file containing `declare module 'jsonwebtoken';`
node_modules/botframework-connector/lib/auth/emulatorValidation.d.ts(8,22): error TS7016: Could not find a declaration file for module 'jsonwebtoken'. '/Users/bill/Dropbox/billba-mbp/botbldr/node_modules/jsonwebtoken/index.js' implicitly has an 'any' type.
  Try `npm install @types/jsonwebtoken` if it exists or add a new declaration (.d.ts) file containing `declare module 'jsonwebtoken';`
6:07:50 AM - Compilation complete. Watching for file changes. 
```

**Comment by Stevenic** [comment] 2018-03-23 20:40
So as a workaround you can just do what it says and add the typing into your package and I'll publish new bits shortly:

```
npm install --save @types/jsonwebtoken
```

The issue is this type is listed as a devDependency in the connector which apparently causes it to not get installed when added as a reference to another package.  Funny given that TypeScript advises you add them as devDependencies.  I need to go through and make sure we're not doing this elsewhere.

**Comment by Stevenic** [comment] 2018-04-17 03:42
This should be fixed with the `M3` bits

**Closed by Stevenic** 2018-04-17 03:42 UTC
Labels: bug
