### ISSUE TITLE
IT (Italian) locale: when employing "numberPrompt", entering\]number (for example "1") , he gets the   E_MISSING_BUNDLE exception

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-js#2916] opened 2020-10-19 20:42 UTC
## Versions
What package version of the SDK are you using.
What nodejs version are you using
What browser version are you using
What os are you using

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

**Comment by joshgummersall** [comment] 2020-10-20 17:25
This looks like a dupe of https://github.com/microsoft/botbuilder-js/issues/2911.

**Closed by joshgummersall** 2020-10-20 17:25 UTC
Labels: bug, needs-triage
