### ISSUE TITLE
[PORT] Proactive auth: trust incoming token url conditionally

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#1890] opened 2020-03-11 00:14 UTC
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3532

# Changed projects
* Microsoft.Bot.Builder

**Comment by Kaiqb** [comment] 2020-03-11 17:36
@stevengum  - this was discussed in the Stand-up meeting. ChrisMu mentioned that Carlos had already made the update. Is that not the case?

**Comment by stevengum** [comment] 2020-03-11 22:27
The linked PR is a parity feature that will align the behavior in the two languages. In JS, users still have to trust the serviceUrl to fetch a token for outgoing requests.

In C#, when using `BotFrameworkAdapter.ContinueConversationAsync()` this is no longer required.

#1889 will change it so that the ServiceUrl is trusted automatically _if_ the bot has an AppId. The unit tests in #1889 account for the scenario that drove microsoft/botbuilder-dotnet#3532.

Because this is just language alignment and not breaking any existing scenarios, I marked it as R9 to not impede the 4.8 release train.

___

#### Testing
I tested [`4.8.0-rc0`](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.8.0-rc0) anonymous proactive messaging via [sample 16](https://github.com/microsoft/BotBuilder-Samples/tree/b47c390c7c5cf58b4a9cc6e7e5d874eecc23b5fd/samples/javascript_nodejs/16.proactive-messages) and @jwiley84 confirmed that it worked for her as well.

**Closed** 2020-03-13 21:30 UTC
Labels: P1, R9, parity with C#
