### ISSUE TITLE
Add an option to allow bots to acquire tokens from a specified tenant

### ISSUE THREAD

**Issue by mingweiw** [Microsoft/botbuilder-js#504] opened 2018-10-01 20:26 UTC
This is the same request as this [dotnet issue](https://github.com/Microsoft/botbuilder-dotnet/issues/999).

**Comment by sgellock** [comment] 2019-02-08 16:44
This issue is a duplicate of https://github.com/Microsoft/botbuilder-dotnet/issues/999.  If that ticket is approved, then a master tracking ticket in botbuilder should be opened to track the various language work

**Closed by sgellock** 2019-02-08 16:44 UTC
Labels: 4.3, Triaged
