### ISSUE TITLE
[Bug] BotFrameworkAdapter.createConversation does not properly populate conversation id

### ISSUE THREAD

**Issue by levinmr** [microsoft/botbuilder-js#1410] opened 2019-11-13 20:51 UTC
## Versions
What package version of the SDK are you using.
4.6

What nodejs version are you using
10.15.3

What browser version are you using
n/a

What os are you using
macOS 10.15.1

What bot connector are you using
Twilio SMS

## Describe the bug
When beginning a proactive conversation with a user, a new conversation must be created with a reference and callback.  The TurnContext passed to the callback has an activity.conversation.id of undefined.  This id is required for storage and further activity calls to work.

## To Reproduce
1. Create a new BotFrameworkAdapter instance, create a conversation with the instance, see the unexpected context

```javascript
const { BotFrameworkAdapter } = require('botbuilder');
const { MicrosoftAppCredentials } = require('botframework-connector');

const botFrameworkAdapter = new BotFrameworkAdapter({
  appId: process.env.MICROSOFT_APP_ID,
  appPassword: process.env.MICROSOFT_APP_PASSWORD
})

const conversationReference = {
  user: { id: '<user phone number>' },
  bot: {
    id: '<bot phone number>',
    name: 'bot'
  },
  conversation: { id: '<user phone number>' },
  channelId: 'sms',
  serviceUrl: 'https://sms.botframework.com'
}

MicrosoftAppCredentials.trustServiceUrl(conversationReference.serviceUrl);
await botFrameworkAdapter.createConversation(
  conversationReference,
  turnContext => {
    console.log(turnContext.activity.conversation.id) 
    // => should be the user phone number but is undefined
  }
);
```

## Expected behavior
TurnContext passed to callback from BotFrameworkAdapter.createConversation call should have an activity with a conversation id of the phone number from the conversation reference.

## Additional context
Running through the debugger, it seems that the adapter's call to the connector client returns a response object with an `Id` key, and the subsequent code expects the key `id` (note the case difference)

Link to the offending code
https://github.com/microsoft/botbuilder-js/blob/22a34be0d936d9aeb7b8450e2331c10cdfa1fd7f/libraries/botbuilder/src/botFrameworkAdapter.ts#L373

[bug]

**Comment by mdrichardson** [comment] 2019-11-14 18:52
@levinmr I can confirm that I can reproduce this. Thanks for the debugging work! I'll forward this on as a bug and we'll get it fixed. As a workaround in the meantime, you should be able to do something like:

```typescript
await botFrameworkAdapter.createConversation(
  conversationReference,
  turnContext => {
    // We know what it *should* be, so let's just set it
    turnContext.activity.conversation.id = turnContext.activity.from.id;
  }
);
```

---

To dev engineer: I wasn't able to repro this in channels other than Twilio. The offending line is as @levinmr stated above. In Twilio, `response` comes back with "response.**I**d", whereas in other channels, it comes back with "response.**i**d", so it gets missed here:
https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkAdapter.ts#L383

I dug around the Intercom Channels Repo and nothing stood out to me.

**Comment by mdrichardson** [comment] 2019-11-14 22:19
@levinmr We've found the cause of the problem (SMS Channels use a different JSON serializer) and I've opened an issue for us to track this internally.

No ETA on the fix yet, but I'll close this for now and update you here once I know more.

Internal users: this is being [tracked here](https://fuselabs.visualstudio.com/Intercom/_workitems/edit/39246/)

**Closed by mdrichardson** 2019-11-14 22:19 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported

**Comment by mdrichardson** [comment] 2019-12-03 17:20
@levinmr We've merged the fix for this into the next release. It should go out this week or early next.
