### ISSUE TITLE
[PORT] Support SSO with skill dialog and expected replies

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-js#2122] opened 2020-04-28 22:32 UTC
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3818

Support SSO with skill dialog and expected replies

# Changed projects
* Microsoft.Bot.Builder.Dialogs
* Microsoft.Bot.Builder
* Microsoft.Bot.Builder.Dialogs.Tests

**Comment by stevengum** [comment] 2020-04-30 00:25
Dupe of #1993

https://github.com/microsoft/botbuilder-js/pull/2127 will address this issue.

**Closed by stevengum** 2020-04-30 00:25 UTC
