### ISSUE TITLE
DatetimePrompt don't resolve natural language in spanish

### ISSUE THREAD

**Issue by VaroJulio** [Microsoft/botbuilder-js#519] opened 2018-10-04 15:22 UTC
Actually, I´m using the BotBuilder V4 preview SDK(4.0.0-preview1.2) (botbuilder, botbuilder-ai, botbuilder-azure, botbuilder-choices, botbuilder-core, botbuilder-dialogs, botbuilder-prompts).

Node version:  v8.11.4

Browser: N/A

OS: Win10

Bug Description:
I have been testing DateTime Prompts with inputs like "Mañana a las 8pm" or "Mañana" or "Hoy" or "Próximo viernes" and the DateTimePrompts can't get the right Date, but when I write inputs in English like "Tomorrow at 8pm", it works.

**Comment by benbrown** [comment] 2018-10-04 20:06
@VaroJulio are you passing in a locale option?

**Comment by stevengum** [comment] 2018-10-04 23:02
@VaroJulio can you provide the code you're using or code that reproduces this outcome?

**Comment by VaroJulio** [comment] 2018-10-05 15:51
this.dialogs.add('fechaRegresoPrompt',new DatetimePrompt(undefined,'es-es'));
await dc.prompt(
            'fechaRegresoPrompt',
            'Por favor dime, ¿Cuál es la fecha de tu vuelo de regreso? ✈. (Ejemplo: mm/dd/yyyy).'
          );

**Comment by stevengum** [comment] 2018-10-15 17:29
@VaroJulio can you provide clarification regarding this bit:

> _... the DateTimePrompts can't get the right Date..._

What is the prompt returning? 

Also, we recommend updating to the latest version of botbuilder. Please note that the 4.0.6 will fix the dependencies for the Recognizers-Text to [1.0.1](https://github.com/Microsoft/botbuilder-js/commit/51053d36ae8189d5c87c2132bd8fbe072cced42a#diff-8ad70ddf73cfe1b66207be74c2492bee) and will change the way you write dialogs so your code would need to be changed to something like this:

```js
// The dialogId is now passed in to the constructor for the dialog
this.dialogs.add(new DatetimePrompt('fechaRegresoPrompt', undefined, 'es-es'));
await dc.prompt(
  'fechaRegresoPrompt',
  'Por favor dime, ¿Cuál es la fecha de tu vuelo de regreso? ✈. (Ejemplo: mm/dd/yyyy).'
);
```

**Comment by sgellock** [comment] 2018-10-18 20:19
resolving due to not response.  if you are able to help us with a repo case, please open a new issue and we'll engage in helping

**Closed by sgellock** 2018-10-18 20:19 UTC
