### ISSUE TITLE
ServiceClientCredentials support for SkillHttpClient

### ISSUE THREAD

**Issue by alopix** [microsoft/botbuilder-js#1628] opened 2020-01-29 11:30 UTC
**Is your feature request related to a problem? Please describe.**
In the old Skill SDK (botbuilder-skills), the `SkillDialog` supported passing in a `IServiceClientCredentials` object, which would be used in the old `SkillHttpTransport ` to allow for adding different kinds of authentication or any type of request transformations when connecting to the skills.
With `SkillHttpClient` (mostly `BotFrameworkHttpClient`) only supports appId and appPassword authentication and nothing else anymore.

**Describe the solution you'd like**
It would be nice to be able to define some kind of middleware (or if you moved from axios to the azure `ms-rest-js` again) in order to transform the outgoing request.

**Describe alternatives you've considered**
There's no alternative as appId and appPassword are not secure enough for us, so we're using api keys in addition.

**Additional context**
-

[enhancement]

**Comment by tonyanziano** [comment] 2020-01-29 19:07
@clearab Can you please comment on this? Thanks!

**Comment by clearab** [comment] 2020-01-30 00:29
Thanks for bringing this to our attention - we'll triage and consider for inclusion in the next release.

**Comment by daveta** [comment] 2020-02-06 19:03
@alopix our next release is R8 scheduled ~March 16..  FYI..

**Comment by clearab** [comment] 2020-02-06 22:19
Need to validate the other language implementations.

**Comment by johnataylor** [comment] 2020-03-03 00:33
@alopix the fix we've landed on in our current R8 release is to align the JavaScript implementation with the C# and introduce a buildCredential protected member function that can be overriden to provide an alternative token factory. Ideally we starting to realize the ICredentialProvider class needs a rethink (apparently it dates from v3) but we would like to postpone a deeper refactoring.

So hopefully this works for you. Please let us know if it doesn't.

**Comment by alopix** [comment] 2020-03-03 08:52
Thanks, but unfortunately that does not really solve the problem.
The solution still only allows for auth via the `Authorization` header which is not what you would have to use for e.g. an AWS Gateway API Key, which has to be provided via the `x-api-key` header instead.

**Comment by johnataylor** [comment] 2020-03-12 16:03
Thanks @alopix.

The changes we made in R8 provide some flexibility in the BotFrameworkHttpClient implementation and makes this consistent with other aspects of our framework. We also aligned the JavaScript model with what we had shipped in C# in R7. This is a consistent and good but minor modification. It doesn't seem to address the issue raised here which is looking for something more fundamental.

Without our current bits the solution for controlling specific HTTP headers would be further down the stack. In C# that means a custom HttpClient which can be handed into this class. (BotFrameworkHttpClient is really an application specific HttpClient - designed to be injectable follow the model of HttpClientFactory introduced in recent ASP.) The problem is focusing on the HttpClient is very C# specific and we would ideally like to be reasonably consistent across languages.

We need to review this design all up and see what we can do to make it more flexible. Reopening and marking as R9.

**Comment by EricDahlvang** [comment] 2020-03-14 02:19
Hi @alopix 

Thanks for raising this issue.  Fortunately, the `buildCredentials` override of 4.8 can be used with a custom `CertificateAppCredentials` enabling using a certificate instead of appid/password, and also setting the x-api-key header in `signRequest` 

Something like:

```javascript
const keyPemFile = './private-key.pem';
const pkFromFile = fs.readFileSync(
    path.resolve(__dirname, keyPemFile),
    { encoding: 'utf8'}
);

const adapterSettings = {
    appId: process.env.MicrosoftAppId,
    // appPassword: process.env.MicrosoftAppPassword,
    certificatePrivateKey: pkFromFile,
    certificateThumbprint: process.env.certificateThumbprint,
};

class SignRequestAppCredentials extends CertificateAppCredentials {
    async signRequest(webResource) {
        if (AppCredentials.isTrustedServiceUrl(webResource.url)) {
            webResource.headers.set('x-api-key', 'key value here');
            const token = await this.getToken();
            return new msrest.TokenCredentials(token).signRequest(webResource);
        }
        return webResource;
    }
}

class BuildCredentialsSkillHttpClient extends SkillHttpClient {
    async buildCredentials(appId, oAuthScope) {
        return new SignRequestAppCredentials(appId, adapterSettings.certificateThumbprint, adapterSettings.certificatePrivateKey, undefined, oAuthScope);
    }
}

const credentialProvider = new SimpleCredentialProvider(process.env.MicrosoftAppId, '');
const conversationIdFactory = new SkillConversationIdFactory();
const skillClient = new BuildCredentialsSkillHttpClient(credentialProvider, conversationIdFactory);
```

4.8RC can be found on myget: https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.8.0

Please give this a try, and let us know if it meets your requirements.

**Closed by EricDahlvang** 2020-03-14 02:19 UTC
Labels: Bot Services, P1, R9, Skills, customer-replied-to, customer-reported, enhancement, investigate

**Comment by alopix** [comment] 2020-05-05 10:31
@EricDahlvang thanks for the sample, unfortunately `signRequest` will never be called as it's not being used inside the `SkillHttpClient` (or rather it's parent `BotFrameworkHttpClient`).
It only ever calls the `getToken` method and ignores the rest of the interface.
Looking at the repo I cannot find a single reference to the `signRequest` method actually being used anymore.

I’m not sure if some of the `AppCredentials` interface isn’t just legacy code from when `botbuilder-skills` was “merged” and the `IServiceClientCredentials` interface was somehow turned into the `AppCredentials`: https://github.com/microsoft/botframework-solutions/blob/master/sdk/typescript/libraries/botbuilder-skills/src/auth/serviceClientCredentials.ts

The legacy `SkillHttpTransport` actually did call the sign method instead of just getting the token: https://github.com/microsoft/botframework-solutions/blob/master/sdk/typescript/libraries/botbuilder-skills/src/http/skillHttpTransport.ts#L55

**Comment by EricDahlvang** [comment] 2020-05-06 21:13
@alopix since `SkillHttpClient` uses axios, a request interceptor should work for setting custom headers on these calls:

```js
const axios = require('axios');
axios.interceptors.request.use(function(config) {
    config.headers['x-api-key'] = process.env.xapikey;
  return config;
}, function(err) {
  return Promise.reject(err);
});
```

`signRequest` is called internally, by `ms-rest-js`: https://github.com/Azure/ms-rest-js/blob/fcc8528c75bc230255fbd902c8682f96b6c9aed6/lib/policies/signingPolicy.ts#L24 So the call is not in the BB codebase.
