### ISSUE TITLE
Random ECONNRESET

### ISSUE THREAD

**Issue by DanielTizon** [microsoft/botbuilder-js#2054] opened 2020-04-17 08:13 UTC
**Versions**

NodeJS v12.13.0
BotBuilder NodeJS SDK v4.8.0

**Describe the bug**

In production for directline channel users, our bot is giving random ECONNRESET errors, and we are not able to reproduce it, because it is really random. It is one example of the error:

`(node:13008) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERRORError: read ECONNRESETat new RestError (D:\home\site\wwwroot\node_modules\botframework-connector\node_modules\@azure\ms-rest-js\dist\msRest.node.js:1397:28)at AxiosHttpClient.<anonymous> (D:\home\site\wwwroot\node_modules\botframework-connector\node_modules\@azure\ms-rest-js\dist\msRest.node.js:1550:35)at step (D:\home\site\wwwroot\node_modules\tslib\tslib.js:139:27)at Object.throw (D:\home\site\wwwroot\node_modules\tslib\tslib.js:120:57)at rejected (D:\home\site\wwwroot\node_modules\tslib\tslib.js:111:69)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)at BotFrameworkAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:660:27)at Generator.throw (<anonymous>)at rejected (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:12:65)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)(node:13008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)(node:13008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

It happens like 20-30 times a day. I have checked this issue:

https://github.com/microsoft/botbuilder-js/issues/1705

But it was closed with no solution, so I have opened another one.

**Comment by mdrichardson** [comment] 2020-04-17 16:25
@DanielTizon I can help with this, but could use some more information:

1. What is the appId for your bot?
2. Do you have some conversationIDs for when this occurred?
3. Is there any way to consistently reproduce this?
4. How is the bot hosted?
5. Has this error always occurred, or has it started occurring more recently?
6. Could you try wrapping the `server.post('/api/messages'...` block in a `try/catch` and copy/pasting any errors from the `catch` statement here?

**Comment by DanielTizon** [comment] 2020-04-20 10:03
Ok @mdrichardson, I can give you that information:

1. b482cec8-2f48-4368-9778-c6a2334f7cff

2. I haven't the conversationID

3. the bot is hosted in Azure like a Bot Service

4. this exact error is happening recently, since we updated to botbuilder v4. We had, maybe, similar issues in v3 with problems related to Directline EU West service going down some times or having high load problems.

5. Ok, done!

Furthermore, I have had this error today, and I have checked the DirectLine channels view of Azure Bot App, and I habe seen a lot of DirectLine problems like this:

```
20/4/2020 11:45:40 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|616f0e1cbefa544aa54898b3b5b0679f.675c46f9_

20/4/2020 11:39:28 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|2f38e9b8d0816a4e911a67cd3cb0f2cf.2930fc55_

20/4/2020 11:19:38 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|03f895d5b0b692458239278fe825cfc6.3d99edd8_

20/4/2020 10:53:42 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|b4ef95fc4d0d7a439be2a4e464f9788a.d0e83870_

20/4/2020 10:16:16 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|356507234e92cf41b3e0419b66281f4c.6d57d994_
```

**Comment by DanielTizon** [comment] 2020-04-20 11:33
I think that this problem with our production bots is related to problems in Microsoft DirectLine Channel:

We are getting more messages like this:

`(node:11308) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERRORError: connect ETIMEDOUT 13.95.93.152:443at new RestError (D:\home\site\wwwroot\node_modules\botframework-connector\node_modules\@azure\ms-rest-js\dist\msRest.node.js:1397:28)at AxiosHttpClient.<anonymous> (D:\home\site\wwwroot\node_modules\botframework-connector\node_modules\@azure\ms-rest-js\dist\msRest.node.js:1550:35)at step (D:\home\site\wwwroot\node_modules\tslib\tslib.js:139:27)at Object.throw (D:\home\site\wwwroot\node_modules\tslib\tslib.js:120:57)at rejected (D:\home\site\wwwroot\node_modules\tslib\tslib.js:111:69)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)at BotFrameworkAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:660:27)at Generator.throw (<anonymous>)at rejected (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:12:65)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)(node:11308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)`

And we have more errors in DirectLine Channels view of Azure:

```
20/4/2020 13:26:31 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|019fbef5c1f88f4e83362817c2c6ba1d.ae29a463_
20/4/2020 13:25:37 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|0fc66d347f6d9041b1ab3b5746d1021d.1adc9e84_
20/4/2020 13:22:51 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|e8a60b4fd89dfd48b8cbe2ceaf872586.3b196b5_
20/4/2020 13:22:41 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|92505655d620534a9303bc7936842cb1.3b193b9_
20/4/2020 13:21:03 | There was an error sending this message to your bot: HTTP status code GatewayTimeout | \|b28d98d9ba630b45aadcf958d478660a.8b8e39ab_
```


Can somebody tell us if Microsoft is having problems other time with DirectLine Channel in any region?

**Comment by mdrichardson** [comment] 2020-04-20 16:25
@DanielTizon I'm not aware of any big outages. Let me look into the backend logs related to your bot and see what I can find. `GatewayTimeout` errors *usually* mean that your bot is taking > 15 seconds to respond or an uncaught error was thrown by the bot. If this started happening after migrating to v4, it could be a bot code error. Not saying it is, but let me look into the logs to try and verify. If you're able to link to your code, I could look at that, too.

**Comment by mdrichardson** [comment] 2020-04-20 17:47
@DanielTizon I'm seeing several different things that are all going to cause the GatewayTimeout error:

1. It looks like there were _several_ app-level changes that interfered with the bot running. I see a lot of `FTPWriteOperation`s. Are you uploading new code, frequently? This will cause 500 errors on our backend (I'm seeing a lot of those) and show as 502s in the Channels tab (which you have).
2. There's also a lot of slow calls to `apigee.net`. Does your bot make external API calls to this prior to responding to the user? If so, that could be a cause of 502s. It wouldn't surprise me if this is what's causing the error you pasted above.
3. I'm also seeing some SNAT port exhaustion--there's too many open connections to your bot at once. Unfortunately, we don't have a good fix for Node bots with this yet. It's being tracked [here](https://github.com/microsoft/botbuilder-js/issues/183). @EricDahlvang is [working on a PR to address this](https://github.com/microsoft/botbuilder-js/issues/2013). It may also help to [upgrade ms-rest-js](https://github.com/microsoft/botbuilder-js/issues/2018) in your bot.

@EricDahlvang Did I miss anything related to the SNAT port exhaustion?

**Comment by EricDahlvang** [comment] 2020-04-20 19:39
It is possible to provide a custom http client with the 1.2.6 version of ms-rest-js used in the sdk:

```js
const customHttpClient = new customHttpClient();
BotFrameworkAdapter.prototype.createConnectorClientInternal = function (serviceUrl, credentials) {
    return new ConnectorClient(credentials, { baseUri: serviceUrl, httpClient: customHttpClient });
};
```

It might be easiest to just duplicate this class: [axiosHttpClient](https://github.com/Azure/ms-rest-js/blob/1.x/lib/axiosHttpClient.ts)  and change line 19: 

```js
axios.create({
  httpAgent: new http.Agent({ keepAlive: true }),
  httpsAgent: new https.Agent({ keepAlive: true }),
});
```

As @mdrichardson mentioned, we are working on upgrading the sdk's version of ms-rest-js, and overcoming port exhaustion should be easier then.

**Comment by DanielTizon** [comment] 2020-04-21 07:03
Thanks for your replies @mdrichardson and @EricDahlvang. 

About the give answers:

**1. It looks like there were several app-level changes that interfered with the bot running. I see a lot of FTPWriteOperations. Are you uploading new code, frequently? This will cause 500 errors on our backend (I'm seeing a lot of those) and show as 502s in the Channels tab (which you have).**

Yes, my team make a lot of code changes and upload it to the server frequently. I don't understand why it should be a problem. Should we to do anything else when we upload a file using FTP? For example, restart WebApp?

**There's also a lot of slow calls to apigee.net. Does your bot make external API calls to this prior to responding to the user? If so, that could be a cause of 502s. It wouldn't surprise me if this is what's causing the error you pasted above.**

It is happening in our development enviroment, but in production all API calls are a lot of faster, and we still have the same problem, and we have been using the same API calls for years with no problem at all.

**I'm also seeing some SNAT port exhaustion--there's too many open connections to your bot at once. Unfortunately, we don't have a good fix for Node bots with this yet. It's being tracked here. @EricDahlvang is working on a PR to address this. This was also a fix for V3 bots. I'm not sure how well it would work for V4.**

I don't know if it could help us, we are going to try the solution given by @EricDahlvang.

Anyways, yesterday we had "connect ETIMEDOUT", even when we were only using sendTyping like this:

`await stepContext.context.sendActivities([{ type: 'typing' }, { type: 'delay', value: 1000 }]);`

**Comment by mdrichardson** [comment] 2020-04-21 15:48
@DanielTizon 

> Yes, my team make a lot of code changes and upload it to the server frequently. I don't understand why it should be a problem. Should we to do anything else when we upload a file using FTP? For example, restart WebApp?

It depends on whether or not the uploads cause the bot to need restarting. For a ZIP deployment, it can cause the bot to be down for a non-insignificant amount of time. Small, simple FTP uploads should be fine. But either way, if it causes the bot to be down, you'll see those errors. I *do* see that a lot of those FTP uploads correlate highly with the bot being unavailable.

> It is happening in our development enviroment, but in production all API calls are a lot of faster, and we still have the same problem, and we have been using the same API calls for years with no problem at all.

I see 49 slow calls on your prod bot in the last 3 days, averaging 9656ms. That's not a lot, but any call over 15 seconds is going to cause those 502s.

> I don't know if it could help us, we are going to try the solution given by @EricDahlvang.

That's your best shot. SNAT port exhaustion is the most likely cause of all of this, but all of these things attribute to it. The fewer total connections you need to maintain at once, the better. This would include FTP writes; Some periods have a LOT of them:

![image](https://user-images.githubusercontent.com/40401643/79885991-d76bc800-83ac-11ea-8b25-a1fca1fe650f.png)

> Anyways, yesterday we had "connect ETIMEDOUT", even when we were only using sendTyping like this

If you can provide conversation IDs or timestamps, I can better look into specific issues like this.

**Comment by mdrichardson** [comment] 2020-04-21 16:03
@DanielTizon 

> Yes, my team make a lot of code changes and upload it to the server frequently. I don't understand why it should be a problem. Should we to do anything else when we upload a file using FTP? For example, restart WebApp?

It depends on whether or not the uploads cause the bot to need restarting. For a ZIP deployment, it can cause the bot to be down for a non-insignificant amount of time. Small, simple FTP uploads should be fine. But either way, if it causes the bot to be down, you'll see those errors. I *do* see that a lot of those FTP uploads correlate highly with the bot being unavailable.

> It is happening in our development enviroment, but in production all API calls are a lot of faster, and we still have the same problem, and we have been using the same API calls for years with no problem at all.

I see 49 slow calls on your prod bot in the last 3 days, averaging 9656ms. That's not a lot, but any call over 15 seconds is going to cause those 502s.

> I don't know if it could help us, we are going to try the solution given by @EricDahlvang.

That's your best shot. SNAT port exhaustion is the most likely cause of all of this, but all of these things attribute to it. The fewer total connections you need to maintain at once, the better. This would include FTP writes; Some periods have a LOT of them:

![image](https://user-images.githubusercontent.com/40401643/79885991-d76bc800-83ac-11ea-8b25-a1fca1fe650f.png)

> Anyways, yesterday we had "connect ETIMEDOUT", even when we were only using sendTyping like this

If you can provide conversation IDs or timestamps, I can better look into specific issues like this.

**Comment by mdrichardson** [comment] 2020-04-21 16:15
@DanielTizon 

> Yes, my team make a lot of code changes and upload it to the server frequently. I don't understand why it should be a problem. Should we to do anything else when we upload a file using FTP? For example, restart WebApp?

It depends on whether or not the uploads cause the bot to need restarting. For a ZIP deployment, it can cause the bot to be down for a non-insignificant amount of time. Small, simple FTP uploads should be fine. But either way, if it causes the bot to be down, you'll see those errors. I *do* see that a lot of those FTP uploads correlate highly with the bot being unavailable.

> It is happening in our development enviroment, but in production all API calls are a lot of faster, and we still have the same problem, and we have been using the same API calls for years with no problem at all.

I see 49 slow calls on your prod bot in the last 3 days, averaging 9656ms. That's not a lot, but any call over 15 seconds is going to cause those 502s.

> I don't know if it could help us, we are going to try the solution given by @EricDahlvang.

That's your best shot. SNAT port exhaustion is the most likely cause of all of this, but all of these things attribute to it. The fewer total connections you need to maintain at once, the better. This would include FTP writes; Some periods have a LOT of them:

![image](https://user-images.githubusercontent.com/40401643/79885991-d76bc800-83ac-11ea-8b25-a1fca1fe650f.png)

> Anyways, yesterday we had "connect ETIMEDOUT", even when we were only using sendTyping like this

If you can provide conversation IDs or timestamps, I can better look into specific issues like this.

**Comment by mdrichardson** [comment] 2020-04-21 16:25
@DanielTizon 

> Yes, my team make a lot of code changes and upload it to the server frequently. I don't understand why it should be a problem. Should we to do anything else when we upload a file using FTP? For example, restart WebApp?

It depends on whether or not the uploads cause the bot to need restarting. For a ZIP deployment, it can cause the bot to be down for a non-insignificant amount of time. Small, simple FTP uploads should be fine. But either way, if it causes the bot to be down, you'll see those errors. I *do* see that a lot of those FTP uploads correlate highly with the bot being unavailable.

> It is happening in our development enviroment, but in production all API calls are a lot of faster, and we still have the same problem, and we have been using the same API calls for years with no problem at all.

I see 49 slow calls on your prod bot in the last 3 days, averaging 9656ms. That's not a lot, but any call over 15 seconds is going to cause those 502s.

> I don't know if it could help us, we are going to try the solution given by @EricDahlvang.

That's your best shot. SNAT port exhaustion is the most likely cause of all of this, but all of these things attribute to it. The fewer total connections you need to maintain at once, the better. This would include FTP writes; Some periods have a LOT of them:

![image](https://user-images.githubusercontent.com/40401643/79885991-d76bc800-83ac-11ea-8b25-a1fca1fe650f.png)

> Anyways, yesterday we had "connect ETIMEDOUT", even when we were only using sendTyping like this

If you can provide conversation IDs or timestamps, I can better look into specific issues like this.

**Comment by DanielTizon** [comment] 2020-04-22 07:41
We have tried the solution given by @EricDahlvang with no luck.

For example, today we are having these kind of errors, some times even only opening the bot, and not receiving the welcome message:

2020-04-22T07:37:57.496Z

(node:15076) UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 500 ERRORError: connect ETIMEDOUT 13.95.93.152:443at new RestError (D:\home\site\wwwroot\node_modules\@azure\ms-rest-js\dist\msRest.node.js:1397:28)at AxiosHttpClient.<anonymous> (D:\home\site\wwwroot\node_modules\@azure\ms-rest-js\dist\msRest.node.js:1550:35)at step (D:\home\site\wwwroot\node_modules\tslib\tslib.js:139:27)at Object.throw (D:\home\site\wwwroot\node_modules\tslib\tslib.js:120:57)at rejected (D:\home\site\wwwroot\node_modules\tslib\tslib.js:111:69)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)at BotFrameworkAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:660:27)at Generator.throw (<anonymous>)at rejected (D:\home\site\wwwroot\node_modules\botbuilder\lib\botFrameworkAdapter.js:12:65)at runMicrotasks (<anonymous>)at processTicksAndRejections (internal/process/task_queues.js:93:5)(node:15076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

**Comment by PACarrascoGomez** [comment] 2020-04-22 08:41
When this error appears we get a 502 in the directline response.

![i2](https://user-images.githubusercontent.com/30193636/79960181-66e4aa00-8485-11ea-91c2-a68fa014139c.png)

**Comment by EricDahlvang** [comment] 2020-04-22 18:01
Please share the code you've used to implement the keepAlive suggestion above.  Looking at the stack trace: 

> ERRORError: connect ETIMEDOUT 13.95.93.152:443at new RestError (D:\home\site\wwwroot\node_modules@azure\ms-rest-js\dist\msRest.node.js:1397:28)at AxiosHttpClient. (D:\home\site\wwwroot\node_modules@azure\ms-rest-js\dist\msRest.node.js:1550:35)

It appears the axios http client from the ms-rest-js library is still in use.

Also, is this bot using LUIS or QnaMaker?  is it calling other external apis?

**Comment by mdrichardson** [comment] 2020-04-22 18:01
@DanielTizon @PACarrascoGomez Are you both working on the same bots, or is this two separate bots/issues?

**Comment by EricDahlvang** [comment] 2020-04-22 21:10
Attached is an example of a `customAxiosHttpClient` with `keepAlive` true for `axiosInstance` (this is a modified version of the ms-rest-js@1.8.14 AxiosHttpClient).  

[customAxiosHttpClient.js.txt](https://github.com/microsoft/botbuilder-js/files/4519014/customAxiosHttpClient.js.txt)

To use it with `BotFrameworkAdapter`:
```js
const { CustomAxiosHttpClient } = require('./customAxiosHttpClient');

const customHttpClient = new CustomAxiosHttpClient();
BotFrameworkAdapter.prototype.createConnectorClientInternal = function (serviceUrl, credentials) {
    return new ConnectorClient(credentials, { baseUri: serviceUrl, httpClient: customHttpClient });
};
```

**Comment by DanielTizon** [comment] 2020-04-23 06:36
Yes @mdrichardson, @PACarrascoGomez and me are working in the same bot. 

And we aren't using LUIS or QnaMaker, we use our own NLU neural network based, and we call it in the code inside onMessage function like this:

```javascript
this.onMessage(async (context, next) => {

    const conversationData = await this.conversationDataAccessor.get(context, {});
    if (conversationData.inicializacionUsuario) {
        await this.getTokenMiddleware(context, next);
        var value = await this.start_NLU(context, next);
        if (value == undefined) { value = await this.finish_NLU(context, next); }
    } else {
        value = await next();
    }

    // Run the Dialog with the new message Activity.
    if (value == undefined) { await this.dialog.run(context, this.dialogSet); }

    // Save state.
    await this.conversationState.saveChanges(context, false);

    // By calling next() you ensure that the next BotHandler is run.
    await next();
});
```

In the start_NLU() function, sometimes we send activities or call to replaceDialog() to start a new dialog depending of the intent detected by our NLU system. I don't know if it is the correct way to do it, because we were using a similar way to do it in middleware when we used botbuilder v3.

And related with the AxiosHttpClient, I'm a bit confused, because we have checked that when you use "npm install" in a clear installation with botbuilder 4.8.0, the version of @azure/ms-rest installed in all dependencies (botframework-connector, botbuilder) is 1.2.6, but @EricDahlvang speak of 1.8.14 version. 

So I have three questions:

1) Should we update @azure/ms-rest to 1.8.14 version for all botbuilder dependencies (botframework-connector, botbuilder)?

2) Should we update the index.js bot code where we instanciate the botFrameworkAdapter with the customAxiosHttpClient instructions given by @EricDahlvang?

3) Should be update the axiosHttpClient of ms-rest library 1.8.14 version, and change line 19 with this:

```
axios.create({
  httpAgent: new http.Agent({ keepAlive: true }),
  httpsAgent: new https.Agent({ keepAlive: true }),
});
```

Thanks in advance!

**Comment by mdrichardson** [comment] 2020-04-23 18:12
> 1. Should we update @azure/ms-rest to 1.8.14 version for all botbuilder dependencies (botframework-connector, botbuilder)?

Yes, you can either fork the repo, update, then install in your bot. Or, you can update the bot* packages in node_modules, then rebuild them.

> 2. Should we update the index.js bot code where we instanciate the botFrameworkAdapter with the customAxiosHttpClient instructions given by @EricDahlvang?

Yes.

> 3. Should be update the axiosHttpClient of ms-rest library 1.8.14 version, and change line 19 with this: <codeFromAbove>

I believe you only need to in index.js. @EricDahlvang?

Assuming your custom NLU functions make HTTP requests, you'll want to implement this kind of thing with them, as well--as well as anything custom you're using to make HTTP requests.

**Comment by EricDahlvang** [comment] 2020-04-23 21:22
Hi @DanielTizon 

I apologize for adding to the confusion with the version numbers.  This should work with the Bot Builder 4.8.0 sdk:

```js
const { CustomAxiosHttpClient } = require('./customAxiosHttpClient');
BotFrameworkAdapter.prototype.createConnectorClientInternal = function(serviceUrl, credentials) {
    return new ConnectorClient(credentials, { baseUri: serviceUrl, httpClient: new CustomAxiosHttpClient() });
};
```

[customAxiosHttpClient.js.txt](https://github.com/microsoft/botbuilder-js/files/4525308/customAxiosHttpClient.js.txt)


The library making the NLU neural network calls should also use an agent with` keepAlive: true`.  Since this is a high volume bot, it is reasonable for all external calls to use an agent which allows for pooling of underlying connections.

**Comment by DanielTizon** [comment] 2020-04-24 07:52
Thanks for the help @EricDahlvang, @mdrichardson. We have applied all these changes and we are monitoring the logs. The next week we'll tell you if we have been able to resolve the problem.

**Comment by DanielTizon** [comment] 2020-04-30 07:22
After 7 days monitoring everything, the number of ECONNRESET has been drastically reduced (6 errors in last 7 days, before it was like 20 errors every day). I guess that the last changes are working well, although like I said we still have some ECONNRESET errors in production bot, could it be related with specific problems on Directline or Microsoft servers?

**Comment by mdrichardson** [comment] 2020-04-30 16:51
@DanielTizon Well, the good news is that I'm no longer seeing *any* SNAT port exhaustion! The bad news is that I'm currently not sure what else is causing the ECONNRESET errors.

I'm still seeing some slow calls to `apigee.net`...25 in the last week. If any of those are done synchronously and cause the bot to take more than 15 seconds to respond, it's going to throw 502 errors--I see 4 of those in the last week.

I'm also seeing a couple of 500 errors. These usually mean either you have some uncaught errors that cause the bot to halt or restart, or somebody is trying to access the bot while it's down (like when uploading new code).

Otherwise, everything is looking pretty good. If you can provide timestamps and/or ConversationIDs of something in particular you'd like me to look at, I might be able to provide better answers.

**Comment by EricDahlvang** [comment] 2020-05-01 00:48
Glad to hear there has been significant improvements.  

You might also be able to use the 'agentkeepalive' library described here: https://blog.botframework.com/2018/03/05/fix-snat-exhaustion-node-js-bots/

and adjust max sockets and timeout settings based on your load and environment.

It might also help to adjust some of the exponential retry policy option values.  In the 4.8 sdk, this can be set by changing the createConnectorClientInternal  prototype, providing custom request policy factories:

**timeoutPolicy.js**
```js
const { BaseRequestPolicy } = require("@azure/ms-rest-js");

module.exports = function timeoutPolicy(requestTimeout) {
    return {
        create: function (nextPolicy, options) {
            return new TimeoutPolicy(nextPolicy, options, requestTimeout);
        }
    };
}

var DEFAULT_CLIENT_REQUEST_TIMEOUT = 1000 * 10;

class TimeoutPolicy extends BaseRequestPolicy {
    constructor(nextPolicy, options, requestTimeout) {
        super(nextPolicy, options);

        function isNumber(n) { return typeof n === "number"; }
        
        this.requestTimeout = isNumber(requestTimeout) ? requestTimeout : DEFAULT_CLIENT_REQUEST_TIMEOUT;
    }

    sendRequest = function(request) {
        var _this = this;
        
        request.timeout = this.requestTimeout;

        return this._nextPolicy.sendRequest(request.clone())
            .catch(function(error) { 

                // If the request.timeout is reached, `timeout of ${ policy.requestTimeout }ms exceeded` will
                const errorIsTimeout = error && error.message && error.message.includes('timeout') && error.message.includes(`${ _this.requestTimeout }ms`);

                if(errorIsTimeout) {
                    error.status = 503; // mimic Service Unavailable, so exponentialRetryPolicy will retry
                }
                return error;
            });
    };
};

```

**requestPolicyHelper.js**
```js
const { deserializationPolicy, exponentialRetryPolicy, systemErrorRetryPolicy, throttlingRetryPolicy, signingPolicy, userAgentPolicy } = require("@azure/ms-rest-js");
const  timeoutPolicy  = require('./TimeoutPolicy');

module.exports = function createRequestPolicyFactories(credentials, options) {
    const factories = [];
    if(options === undefined) {
        options = [];
    }
  
    if (options.generateClientRequestIdHeader) {
        factories.push(generateClientRequestIdPolicy(options.clientRequestIdHeaderName));
    }
    if (credentials) {
        factories.push(signingPolicy(credentials));
    }

    factories.push(userAgentPolicy({ value: options.userAgent }));
    
    if (!options.noRetryPolicy) {
        //retryCount, retryInterval, minRetryInterval, maxRetryInterval
        factories.push(exponentialRetryPolicy(options.retryCount, options.retryInterval, options.minRetryInterval, options.maxRetryInterval));
        // timeout per call, in seconds
        factories.push(timeoutPolicy(options.requestTimeout));
        
        factories.push(systemErrorRetryPolicy());
        factories.push(throttlingRetryPolicy());
    }
    factories.push(deserializationPolicy(options.deserializationContentTypes));
    return factories;
}
```



```js
const  createRequestPolicyFactories  = require('./RequestPolicyHelper');
const { CustomAxiosHttpClient } = require('./customAxiosHttpClient');
const { CustomAxiosHttpClient } = require('./customAxiosHttpClient');

BotFrameworkAdapter.prototype.createConnectorClientInternal = function (serviceUrl, credentials) {

    const factories = createRequestPolicyFactories(credentials, 
        {
            requestTimeout: 1000 * 5, 
            retryCount: 4, 
            retryInterval: 1000 * 2, 
            minRetryInterval: 1000 * 2, 
            maxRetryInterval: 1000 * 6 
        });
    const client = new ConnectorClient(credentials, { baseUri: serviceUrl, httpClient: new CustomAxiosHttpClient(), requestPolicyFactories: factories });

    return client;
};
```

And adjust the intervals as required by your configuration.

**Comment by DanielTizon** [comment] 2020-05-05 08:22
Thanks for all your help guys. Last 7 days, we only have got 2 ECONNRESET errors, so we are going to investigate if these few errors can be related with any problem with the slow calls to ApiGee or 500 errors like @mdrichardson suggest.

**Comment by mdrichardson** [comment] 2020-05-05 15:59
@DanielTizon I see 3 500 errors in the last week and they don't seem to be related to slow calls to `ApiGee`. I'm not seeing anything on the backend that indicates that it's service, related, either. It *looks* like your bot is throwing an uncaught error or something, but it's tough to say without logs.

Are you able to provide some logs and/or particular conversation IDs or timestamps to look into? Or should we close this?

**Comment by EricDahlvang** [comment] 2020-05-06 19:38
I think we can close this issue, since we have determined the underlying problem to be socket exhaustion.  Ensuring all outgoing calls use a keepalive agent as well as adjusting timeouts and agent keepalive settings to fit your specific environment should help get through remaining issues.

**Closed by EricDahlvang** 2020-05-06 19:38 UTC
Labels: Bot Services, DEP0018, customer-replied-to, customer-reported
