### ISSUE TITLE
Oauth Prompt: Bug in try...catch block in recognizeToken function 

### ISSUE THREAD

**Issue by ChepkorirBrenda** [microsoft/botbuilder-js#1054] opened 2019-07-12 15:20 UTC
## Versions
What package version of the SDK are you using.
v4.5.0

What nodejs version are you using
v8.9.4

What os are you using
MSFT Windows

## Describe the bug
App terminates with an "Unexpected token error (this token ' { ')" on line 235 in the oauthPrompt.js during the oauth flow.

## Expected behavior
App to start and stay alive.

[bug]

**Comment by amistry79** [comment] 2019-07-15 12:16
I am facing the same issue and not able to run the bot. We are completely blocked due to this error.

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder-dialogs\lib\prompts\index.js:19:10)
Mon Jul 15 2019 12:00:20 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
D:\home\site\wwwroot\node_modules\botbuilder-dialogs\lib\prompts\oauthPrompt.js:235

**Comment by ChepkorirBrenda** [comment] 2019-07-15 12:46
I reverted back to v4.4.0 for the botbuilder-dialogs package as I wait for the solution. App runs as expected.

**Comment by amistry79** [comment] 2019-07-16 04:27
Yes, I also reverted to v4.40 for botbuilder-* package as I wait for a solution. App run as expected now.  When can we expect the fix?

**Comment by montacerdk** [comment] 2019-07-18 10:27
I am facing the same issue, I reverted the `botbuilder-dialogs` package to `4.4.0`.

**Comment by mdrichardson** [comment] 2019-07-18 22:13
I submitted a PR for this (linked above). I'd imagine it will go in the next release.

**Comment by cleemullins** [comment] 2019-07-23 17:59
I'm caught up on this issue now. I see @mdrichardson PR, and am evaluating. 

We should be able to get this fixed+released shortly.

**Comment by cleemullins** [comment] 2019-07-23 18:56
Status update:
The PR has been merged to master. 
The PR has been picked to the 4.5 Branch.

The 4.5.2 JS Build is done and [packages are found on our build server](https://botbuilder.myget.org/feed/botbuilder-v4-js-daily/package/npm/botbuilder/4.5.2).

I'm working on regression testing the build, and will push to NPM once that's done.

**Comment by cleemullins** [comment] 2019-07-23 22:42
The 4.5.2 SDK has been pushed to NPM. As far as I know, this bug is now fixed, and I can close the issue.

**Closed by cleemullins** 2019-07-23 22:42 UTC
Labels: Bug, Customer
