### ISSUE TITLE
postBack sends a Message activity with undefined text

### ISSUE THREAD

**Issue by navzam** [Microsoft/botbuilder-js#268] opened 2018-06-05 22:31 UTC
```
async function botLogic(context: TurnContext) {
    if (context.activity.type === ActivityTypes.Message) {
        const button: CardAction = {
            type: 'postBack',
            title: 'Button',
            value: { foo: 'bar' }
        };
        const card = CardFactory.heroCard('This is a card', [], [button]);
        const msg = MessageFactory.attachment(card);
        await context.sendActivity(msg);
    }
}
```

With the code above, when you click on the button in the emulator, the activity sent to your bot has type `message` but no `text` property. I expect message activities to always include `text`, especially since `text` is a required field in the `Activity` type definition.

Or maybe `text` should be optional in `Activity`. It'd be annoying to handle `text` being potentially undefined, but it does seem more correct since other activity types don't contain it.

**Comment by Stevenic** [comment] 2018-06-08 21:49
You have no activity text because you're passing an object for the `value` of your action instead of a string. Do you get the object back at all?  Which channels are you trying?

**Comment by navzam** [comment] 2018-06-08 21:53
The `postBack` works fine, but it caused my code to crash in places where I had assumed that `text` would be present in message activities. My concern is more about the type of `text` being `string` instead of `string | undefined`

**Comment by Stevenic** [comment] 2018-06-08 21:58
The issue is those schema files are automatically generated from Swagger and the issue is we use `Activity` for both inbound & outbound activities which have different required fields. On top of that there are like 10 - 15 different activity types so the schema for `Activity` will never be accurate. That's why we pass `Partial<Activity>` around everywhere because the only real required field is `type`.

Can I ask again. Did the object get posted back? If so which field? `activity.value`?

**Comment by navzam** [comment] 2018-06-08 22:05
Yes, it got posted back in `context.activity.value`

**Comment by Stevenic** [comment] 2018-06-08 22:18
Which channel? I don't know if that's well defined... @dandriscoll

**Comment by navzam** [comment] 2018-06-08 22:40
Emulator

**Comment by dandriscoll** [comment] 2018-06-08 22:41
The behavior is pretty well-defined but it can be a lot to dig through. We have reference documentation here: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-activity-spec?view=azure-bot-service-3.0

In short, though, activity.Text is not required for message activities, as buttons of particular type (e.g. messageBack) may simply omit the text field. (You, as the developer, get to choose which fields are populated on the button, especially in the case of newer buttons like messageBack).

**Comment by Stevenic** [comment] 2018-08-17 18:30
Closing this for now since the current behavior is by design.

**Closed by Stevenic** 2018-08-17 18:30 UTC
Labels: Approved
