### ISSUE TITLE
User is from different region in `handleTeamsSigninVerifyState`

### ISSUE THREAD

**Issue by gauravsaralMs** [microsoft/botbuilder-js#3298] opened 2021-02-11 07:49 UTC
## Versions
What package version of the SDK are you using. 4.7.2
What nodejs version are you using 12.16
What browser version are you using N/A
What os are you using. Linux

## Describe the bug
This is not a consistent repro but in our bot sometimes during execution of `handleTeamsSigninVerifyState` we are getting an error `RestError: User is from different region`

One of the customers hitting this issue helped with this information

> we are running an educational Teams installation in Germany which is hosted on German Microsoft servers (due to German/European data protection laws) as far as I know. Maybe this helps.

## To Reproduce
Users have reported this behavior in the teams sign in flow 
During the course of sign in (when verification token is verified) then users get this error

## Expected behavior
Sign in should just work

## Screenshots
N/A

## Additional context
N/A

**Comment by EricDahlvang** [comment] 2021-02-23 18:15
Hi @gauravsaralMs 

Thank you for reporting this issue.

Would you be able to provide us with a stack trace, when the error occurs? Does the exception happen during the call from the bot to the Bot Framework Auth service, or when the bot attempts to send a message after the auth is complete?

**Comment by gauravsaralMs** [comment] 2021-02-25 08:52
@EricDahlvang : sharing stack trace

`
unhandled error: RestError: User is from different region\\n    at new RestError (/workdir/node_modules/botframework-connector/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1397:28)\\n    at /workdir/node_modules/botframework-connector/node_modules/@azure/ms-rest-js/dist/msRest.node.js:1849:37\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\\n    at async TeamsGithubBot.handleTeamsSigninVerifyStateInternal (/workdir/dist/lib/chatops/msteams/teams-github-bot.js:292:30)\\n    at async TeamsGithubBot.handleTeamsSigninVerifyState (/workdir/dist/lib/chatops/msteams/teams-github-bot.js:277:9) {\\n  code: 'BadArgument',\\n  statusCode: 403,\\n  request: WebResource {\\n    streamResponseBody: false,\\n    url: 'https://smba.trafficmanager.net/emea/v3/conversations',\\n    method: 'POST',\\n    headers: HttpHeaders { _headersMap: [Object] },\\n    body: '{\\"isGroup\\":false,\\"bot\\":{\\"id\\":\\"66341\\"},\\"members\\":[{\\"id\\":\\"29:18dJOu1tHtFWs3wZZsGa5IvKoYa2D2LAolHyMurrRxf9ghJdOzZwHkeaICmj-dLXb-9tdJh93E-iILIpIDYUBgw\\",\\"name\\":\\"********\\",\\"aadObjectId\\":\\"********-9dd0-474f-a398-9449ab01adbd\\"}],\\"tenantId\\":\\"*******-42bc-46a3-b004-369735c3acf9\\",\\"activity\\":null,\\"channelData\\":null}',\\n    query: undefined,\\n    formData: undefined,\\n    withCredentials: false,\\n    abortSignal: undefined,\\n    timeout: 0,\\n    onUploadProgress: undefined,\\n    onDownloadProgress: undefined,\\n    operationSpec: {\\n      httpMethod: 'POST',\\n      path: 'v3/conversations',\\n      requestBody: [Object],\\n      responses: [Object],\\n      serializer: [Serializer]\\n    }\\n  },\\n  response: {\\n    body: '{\\"error\\":{\\"code\\":\\"BadArgument\\",\\"message\\":\\"User is from different region\\"}}',\\n    headers: HttpHeaders { _headersMap: [Object] },\\n    status: 403\\n  },\\n  body: {\\n    error: { code: 'BadArgument', message: 'User is from different region' }\\n  }\\n}","time":"2021-02-25T08:34:49.778Z","v":0} kube_syslog_append=true
`

from our code we can see it is coming in the implementation of `handleTeamsSigninVerifyState`
I believe this is coming when we are trying to create a conversation with the user (we do this when sign-in ends)
`createConversation`

**Comment by EricDahlvang** [comment] 2021-03-02 23:07
Thank you for providing the stack trace @gauravsaralMs 

This looks like a duplicate of https://github.com/microsoft/botbuilder-js/issues/3280

Closing 3298, since 3280 is tracking this issue.

**Closed by EricDahlvang** 2021-03-02 23:07 UTC
Labels: bug, needs-triage
